# Generated by Django 6.0.4 on 2026-05-20 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_urls', models.JSONField(default=list, help_text='Array of target competitor domain strings.')),
                ('market_positioning_landscape', models.JSONField(default=dict, help_text='Synthesized themes, identified gaps, and keywords.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Competitor Audit',
                'verbose_name_plural': 'Competitor Audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConflictEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adversary_party_name', models.CharField(max_length=255)),
                ('matter_description', models.TextField()),
                ('conflict_status', models.CharField(choices=[('CLEAR', 'Clear'), ('FLAGGED', 'Flagged')], default='CLEAR', max_length=10)),
                ('confidence_score', models.FloatField()),
                ('system_rationale', models.TextField()),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conflict Evaluation',
                'verbose_name_plural': 'Conflict Evaluations',
            },
        ),
        migrations.CreateModel(
            name='LeadICPScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_url', models.URLField(max_length=500)),
                ('icp_definition_text', models.TextField(help_text='The core definition of the target client profile.')),
                ('icp_alignment_score', models.FloatField(help_text='Calculated vector similarity score between 0.0 and 1.0.')),
                ('qualification_signals', models.JSONField(default=dict, help_text='Structured dict containing firmographics, pain points, etc.')),
                ('recommended_outreach_angle', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead ICP Score',
                'verbose_name_plural': 'Lead ICP Scores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(default='Commercial Lease Agreement', max_length=255)),
                ('governing_jurisdiction', models.CharField(max_length=255)),
                ('termination_penalty_months', models.IntegerField(default=0)),
                ('late_fee_percentage', models.FloatField(default=0.0)),
                ('annual_escalation_rate', models.FloatField(default=0.0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Legal Contract',
                'verbose_name_plural': 'Legal Contracts',
            },
        ),
        migrations.CreateModel(
            name='RiskFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('issue', models.TextField()),
                ('original_text_snippet', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='legal_api.legalcontract')),
            ],
            options={
                'verbose_name': 'Risk Flag',
                'verbose_name_plural': 'Risk Flags',
            },
        ),
    ]
