# Generated by Django 6.0.4 on 2026-05-20 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Article Category',
                'verbose_name_plural': 'Article Categories',
            },
        ),
        migrations.CreateModel(
            name='ArticlePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content_body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under AI Review'), ('published', 'Published')], default='draft', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('zelda_seo_analytics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zelda_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zelda_articles', to='zelda_api.articlecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(default='Remote', max_length=150)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract / Freelance')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('intern', 'Internship'), ('junior', 'Junior / Associate'), ('mid', 'Mid-Level'), ('senior', 'Senior / Lead'), ('executive', 'C-Suite / Executive')], default='mid', max_length=20)),
                ('description_text', models.TextField()),
                ('skills_required', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zelda_posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter_text', models.TextField(blank=True, null=True)),
                ('resume_file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('current_stage', models.CharField(choices=[('applied', 'Applied / Ingested'), ('screening', 'Zelda AI Screening'), ('interview', 'Interviewing'), ('offered', 'Offer Extended'), ('rejected', 'Archived')], default='applied', max_length=20)),
                ('zelda_match_score', models.FloatField(default=0.0)),
                ('extracted_talent_profile', models.JSONField(blank=True, default=dict)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zelda_job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zelda_applications', to='zelda_api.joblisting')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
