# Generated by Django 6.0.4 on 2026-05-25 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='articlepost',
            name='view_count',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='JobListing',
        ),
    ]
