# Generated by Django 6.0.4 on 2026-06-19 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0003_documentsource_documentchunk_intelligenceinsight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('crunchbase', 'Crunchbase'), ('linkedin', 'LinkedIn'), ('sec', 'SEC EDGAR'), ('web', 'Web Scraping'), ('news', 'News Articles'), ('domain', 'Domain WHOIS'), ('jobs', 'Job Boards'), ('news_api', 'News API'), ('corporate', 'Corporate Filings'), ('other', 'Other Source')], max_length=20)),
                ('source_name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, help_text='API key if needed', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'External Data Source',
                'verbose_name_plural': 'External Data Sources',
            },
        ),
        migrations.CreateModel(
            name='ClaimedDatapoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('revenue', 'Revenue'), ('arr', 'Annual Recurring Revenue (ARR)'), ('customers', 'Customer Count'), ('growth_rate', 'Growth Rate (%)'), ('employees', 'Employee Count'), ('funding_raised', 'Funding Raised'), ('market_share', 'Market Share'), ('user_count', 'User Count'), ('engagement', 'Engagement Metric'), ('churn', 'Churn Rate'), ('team_size', 'Team Size'), ('office_locations', 'Office Locations'), ('countries', 'Countries Served'), ('other', 'Other Metric')], max_length=50)),
                ('claimed_value', models.CharField(help_text="E.g., '500', '$1M', '200%'", max_length=255)),
                ('claimed_value_numeric', models.FloatField(blank=True, help_text='Numeric value for comparison', null=True)),
                ('unit', models.CharField(blank=True, help_text="E.g., 'customers', '$', '%'", max_length=50)),
                ('time_period', models.CharField(blank=True, help_text="E.g., 'YoY', 'Q3 2024'", max_length=100)),
                ('source_chunk', models.CharField(blank=True, help_text='Which slide/section in deck', max_length=255)),
                ('confidence_in_extraction', models.FloatField(default=0.7, help_text='How confident are we we extracted this correctly')),
                ('extraction_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_datapoints', to='zelda_api.documentsource')),
            ],
            options={
                'ordering': ['category', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservedDatapoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('revenue', 'Revenue'), ('arr', 'Annual Recurring Revenue (ARR)'), ('customers', 'Customer Count'), ('growth_rate', 'Growth Rate (%)'), ('employees', 'Employee Count'), ('funding_raised', 'Funding Raised'), ('market_share', 'Market Share'), ('user_count', 'User Count'), ('engagement', 'Engagement Metric'), ('churn', 'Churn Rate'), ('team_size', 'Team Size'), ('office_locations', 'Office Locations'), ('countries', 'Countries Served'), ('other', 'Other Metric')], max_length=50)),
                ('observed_value', models.CharField(max_length=255)),
                ('observed_value_numeric', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('time_period', models.CharField(blank=True, max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('source_date', models.DateField(blank=True, help_text='When this data was published', null=True)),
                ('source_credibility', models.FloatField(default=0.8, help_text='0.0-1.0 how much we trust this source')),
                ('extraction_method', models.CharField(choices=[('api', 'API Call'), ('web_scrape', 'Web Scraping'), ('manual', 'Manual Entry'), ('filing', 'Corporate Filing')], default='api', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observed_datapoints', to='zelda_api.documentsource')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zelda_api.externaldatasource')),
            ],
            options={
                'ordering': ['-source_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TruthDeltaAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrepancy_percent', models.FloatField(help_text='Absolute % difference between claimed and observed')),
                ('discrepancy_level', models.CharField(choices=[('none', 'None (0-5%)'), ('low', 'Low (5-20%)'), ('medium', 'Medium (20-50%)'), ('high', 'High (50-100%)'), ('critical', 'Critical (>100%)')], max_length=20)),
                ('is_inflated', models.BooleanField(help_text='Is claimed value higher than observed?')),
                ('is_deflated', models.BooleanField(help_text='Is claimed value lower than observed?')),
                ('flag_level', models.CharField(choices=[('green', 'Verified - Matches Data'), ('yellow', 'Caution - Minor Discrepancy'), ('orange', 'Warning - Significant Discrepancy'), ('red', 'Alert - Major Red Flag')], default='yellow', max_length=20)),
                ('explanation', models.TextField(help_text='Why this is flagged')),
                ('importance_weight', models.FloatField(default=1.0, help_text='How important is this metric? Revenue=1.0, Team=0.6, etc')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truth_analyses', to='zelda_api.claimeddatapoint')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truth_delta_analyses', to='zelda_api.documentsource')),
                ('observed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truth_analyses', to='zelda_api.observeddatapoint')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-flag_level', '-discrepancy_percent'],
            },
        ),
        migrations.CreateModel(
            name='TruthDeltaScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_truth_score', models.FloatField(help_text='0-100: Overall credibility score')),
                ('claims_analyzed', models.IntegerField(default=0, help_text='How many claims were analyzed')),
                ('claims_verified', models.IntegerField(default=0, help_text='How many claims matched external data')),
                ('claims_flagged', models.IntegerField(default=0, help_text='How many claims have discrepancies')),
                ('green_count', models.IntegerField(default=0)),
                ('yellow_count', models.IntegerField(default=0)),
                ('orange_count', models.IntegerField(default=0)),
                ('red_count', models.IntegerField(default=0)),
                ('credibility_risk', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=20)),
                ('recommendation_adjustment', models.CharField(blank=True, help_text="E.g., 'downgrade_from_consider_to_pass'", max_length=50)),
                ('summary', models.TextField(help_text='Human-readable summary of findings')),
                ('key_findings', models.TextField(help_text='Bullet points of main discrepancies')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='truth_delta_score', to='zelda_api.documentsource')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('claimed_created', 'Claim Created'), ('observed_created', 'Observed Data Added'), ('analysis_created', 'Analysis Performed'), ('flag_updated', 'Flag Level Changed'), ('verified', 'Manually Verified'), ('score_calculated', 'Score Calculated')], max_length=50)),
                ('details', models.TextField()),
                ('change_summary', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='zelda_api.documentsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
