# Generated by Django 6.0.4 on 2026-06-19 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0004_externaldatasource_claimeddatapoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruthDeltaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_truth_score', models.FloatField(default=0.0)),
                ('credibility_risk', models.CharField(default='unknown', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zelda_api.documentsource')),
            ],
        ),
    ]
