# Generated by Django 6.0.4 on 2026-06-19 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0005_truthdeltareport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255)),
                ('attribute', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('time_period', models.CharField(blank=True, max_length=50)),
                ('source_type', models.CharField(default='pitch_deck', max_length=50)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('text_excerpt', models.TextField()),
                ('chunk_hash', models.CharField(max_length=128)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('extraction_date', models.DateTimeField(auto_now_add=True)),
                ('extracted_by', models.CharField(default='intelligence_pipeline_v3', max_length=100)),
                ('verification_status', models.CharField(default='unverified', max_length=20)),
                ('manual_review_required', models.BooleanField(default=False)),
                ('manual_review_notes', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_assertions', to='zelda_api.documentsource')),
            ],
        ),
        migrations.CreateModel(
            name='ContradictionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_value', models.CharField(max_length=255)),
                ('observed_value', models.CharField(max_length=255)),
                ('discrepancy_percent', models.FloatField(blank=True, null=True)),
                ('discrepancy_direction', models.CharField(blank=True, max_length=50)),
                ('alert_level', models.CharField(default='medium', max_length=20)),
                ('requires_manual_review', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('analyst_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('external_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zelda_api.externaldatasource')),
                ('conflicting_assertion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zelda_api.factassertion')),
                ('fact_assertion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='zelda_api.factassertion')),
            ],
        ),
        migrations.AddIndex(
            model_name='factassertion',
            index=models.Index(fields=['entity_name', 'attribute'], name='zelda_api_f_entity__a8b68e_idx'),
        ),
        migrations.AddIndex(
            model_name='factassertion',
            index=models.Index(fields=['verification_status'], name='zelda_api_f_verific_cdd263_idx'),
        ),
    ]
