# Generated by Django 6.0.4 on 2026-06-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0006_factassertion_contradictionalert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsource',
            name='raw_text_full',
            field=models.TextField(blank=True, default=''),
        ),
    ]
