# Generated by Django 6.0.4 on 2026-07-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0007_documentsource_raw_text_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencememo',
            name='investment_readiness',
            field=models.TextField(blank=True, help_text='0-100 readiness score with strengths/weaknesses'),
        ),
        migrations.AddField(
            model_name='intelligencememo',
            name='questions_for_management',
            field=models.TextField(blank=True, help_text='Open questions the deck does not answer'),
        ),
    ]
