# Generated by Django 6.0.4 on 2026-07-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0008_intelligencememo_investment_readiness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contradictionalert',
            name='analyst_assigned',
        ),
        migrations.RemoveField(
            model_name='contradictionalert',
            name='conflicting_assertion',
        ),
        migrations.RemoveField(
            model_name='contradictionalert',
            name='external_source',
        ),
        migrations.RemoveField(
            model_name='contradictionalert',
            name='fact_assertion',
        ),
        migrations.RemoveIndex(
            model_name='factassertion',
            name='zelda_api_f_entity__a8b68e_idx',
        ),
        migrations.RemoveIndex(
            model_name='factassertion',
            name='zelda_api_f_verific_cdd263_idx',
        ),
        migrations.RemoveField(
            model_name='truthdeltaanalysis',
            name='claimed',
        ),
        migrations.RemoveField(
            model_name='truthdeltaanalysis',
            name='document',
        ),
        migrations.RemoveField(
            model_name='truthdeltaanalysis',
            name='observed',
        ),
        migrations.RemoveField(
            model_name='truthdeltaanalysis',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='truthdeltascore',
            name='document',
        ),
        migrations.RemoveField(
            model_name='verificationauditlog',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='verificationauditlog',
            name='document',
        ),
        migrations.AddField(
            model_name='claimeddatapoint',
            name='chunk_hash',
            field=models.CharField(blank=True, help_text='Hash of the source chunk, for change detection/dedup', max_length=128),
        ),
        migrations.AddField(
            model_name='claimeddatapoint',
            name='page_number',
            field=models.IntegerField(blank=True, help_text="Page this claim's source chunk came from", null=True),
        ),
        migrations.AddField(
            model_name='claimeddatapoint',
            name='text_excerpt',
            field=models.TextField(blank=True, help_text='Full source chunk text this claim was extracted from'),
        ),
        migrations.DeleteModel(
            name='ContradictionAlert',
        ),
        migrations.RemoveField(
            model_name='factassertion',
            name='document',
        ),
        migrations.DeleteModel(
            name='TruthDeltaAnalysis',
        ),
        migrations.DeleteModel(
            name='TruthDeltaScore',
        ),
        migrations.DeleteModel(
            name='VerificationAuditLog',
        ),
        migrations.DeleteModel(
            name='FactAssertion',
        ),
    ]
