# Generated by Django 6.0.4 on 2026-07-03 19:42

import django.db.models.deletion
import zelda_api.protocol
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0009_remove_contradictionalert_analyst_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsource',
            name='document_type',
            field=models.CharField(choices=[('pitch_deck', 'Pitch Deck'), ('financial_model', 'Financial Model'), ('business_plan', 'Business Plan'), ('whitepaper', 'Whitepaper'), ('research', 'Research Report'), ('portfolio', 'Investor Portfolio'), ('business_valuation', 'Business Valuation Request'), ('other', 'Other')], default='pitch_deck', max_length=20),
        ),
        migrations.CreateModel(
            name='BusinessValuationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_overview', models.TextField(blank=True)),
                ('financial_summary', models.TextField(blank=True)),
                ('risk_report', models.TextField(blank=True)),
                ('valuation_summary', models.TextField(blank=True)),
                ('valuation_low', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valuation_high', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_report', to='zelda_api.documentsource')),
            ],
            options={
                'verbose_name': 'Business Valuation Report',
                'verbose_name_plural': 'Business Valuation Reports',
            },
            bases=(zelda_api.protocol.FoundryStandardMixin, models.Model),
        ),
    ]
