# Generated by Django 6.0.4 on 2026-07-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0010_alter_documentsource_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsource',
            name='is_hidden_by_staff',
            field=models.BooleanField(default=False, help_text='Hides this document from everyone except the owner and staff.'),
        ),
    ]
