# Generated by Django 6.0.4 on 2026-07-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0011_documentsource_is_hidden_by_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truthdeltareport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='truthdeltareport',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='truthdeltareport',
            name='overall_truth_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
