# Generated by Django 6.0.4 on 2026-07-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0012_alter_truthdeltareport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimeddatapoint',
            name='category',
            field=models.CharField(choices=[('revenue', 'Revenue'), ('arr', 'Annual Recurring Revenue (ARR)'), ('customers', 'Customer Count'), ('growth_rate', 'Growth Rate (%)'), ('employees', 'Employee Count'), ('funding_raised', 'Funding Raised'), ('market_share', 'Market Share'), ('market_size', 'Total Addressable Market Size'), ('user_count', 'User Count'), ('engagement', 'Engagement Metric'), ('churn', 'Churn Rate'), ('team_size', 'Team Size'), ('office_locations', 'Office Locations'), ('countries', 'Countries Served'), ('other', 'Other Metric')], max_length=50),
        ),
        migrations.AlterField(
            model_name='observeddatapoint',
            name='category',
            field=models.CharField(choices=[('revenue', 'Revenue'), ('arr', 'Annual Recurring Revenue (ARR)'), ('customers', 'Customer Count'), ('growth_rate', 'Growth Rate (%)'), ('employees', 'Employee Count'), ('funding_raised', 'Funding Raised'), ('market_share', 'Market Share'), ('market_size', 'Total Addressable Market Size'), ('user_count', 'User Count'), ('engagement', 'Engagement Metric'), ('churn', 'Churn Rate'), ('team_size', 'Team Size'), ('office_locations', 'Office Locations'), ('countries', 'Countries Served'), ('other', 'Other Metric')], max_length=50),
        ),
    ]
