# Generated by Django 6.0.4 on 2026-07-16 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0013_alter_claimeddatapoint_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClarificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('revenue', 'Revenue'), ('arr', 'Annual Recurring Revenue (ARR)'), ('customers', 'Customer Count'), ('growth_rate', 'Growth Rate (%)'), ('employees', 'Employee Count'), ('funding_raised', 'Funding Raised'), ('market_share', 'Market Share'), ('market_size', 'Total Addressable Market Size'), ('user_count', 'User Count'), ('engagement', 'Engagement Metric'), ('churn', 'Churn Rate'), ('team_size', 'Team Size'), ('office_locations', 'Office Locations'), ('countries', 'Countries Served'), ('other', 'Other Metric')], max_length=50)),
                ('message', models.TextField(blank=True, help_text='What the investor/buyer wants clarified')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Response'), ('RESPONDED', 'Responded'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=10)),
                ('response_text', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarification_requests', to='zelda_api.truthdeltareport')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarification_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
