# Generated by Django 6.0.4 on 2026-07-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0016_valuationpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsource',
            name='valuation_tier',
            field=models.CharField(choices=[('preview', 'Preview'), ('full', 'Full')], default='full', max_length=10),
        ),
    ]
