# Generated by Django 6.0.4 on 2026-07-20 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0017_documentsource_valuation_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityVerificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('domain_registered_date', models.DateField(blank=True, null=True)),
                ('domain_lookup_error', models.CharField(blank=True, help_text="Short, user-facing reason the domain lookup didn't produce a date — never a raw exception.", max_length=255)),
                ('claimed_founding_year', models.PositiveIntegerField(blank=True, null=True)),
                ('timeline_flags', models.JSONField(blank=True, default=list, help_text='Plain-language mismatches between the claimed founding year and external signals.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_verification_reports', to='zelda_api.documentsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
