# Generated by Django 6.0.4 on 2026-08-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0018_entityverificationreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencememo',
            name='base_case',
            field=models.TextField(blank=True, help_text='Most likely outcome given disclosed facts and trajectory'),
        ),
        migrations.AddField(
            model_name='intelligencememo',
            name='bear_case',
            field=models.TextField(blank=True, help_text='Strongest evidence-grounded case AGAINST investing'),
        ),
        migrations.AddField(
            model_name='intelligencememo',
            name='bull_case',
            field=models.TextField(blank=True, help_text='Strongest evidence-grounded case FOR investing'),
        ),
        migrations.AddField(
            model_name='intelligencememo',
            name='key_concerns',
            field=models.TextField(blank=True, help_text='2-4 evidence-cited concerns/gaps against investment'),
        ),
        migrations.AddField(
            model_name='intelligencememo',
            name='key_strengths',
            field=models.TextField(blank=True, help_text='2-4 evidence-cited strengths supporting investment'),
        ),
        migrations.AddField(
            model_name='intelligencememo',
            name='what_would_change_decision',
            field=models.TextField(blank=True, help_text='The single most important missing piece of evidence'),
        ),
        migrations.AddField(
            model_name='intelligencememo',
            name='zelda_advantage',
            field=models.TextField(blank=True, help_text='What this evidence-grounded pass surfaced that a generic AI summary would likely miss'),
        ),
    ]
