# Generated by Django 6.0.4 on 2026-08-31 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0019_intelligencememo_base_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intelligencememo',
            name='recommendation',
            field=models.CharField(choices=[('STRONG_INVEST', 'Strong Invest'), ('INVEST', 'Invest'), ('NEEDS_REVIEW', 'Needs Review'), ('PASS', 'Pass')], default='NEEDS_REVIEW', max_length=20),
        ),
    ]
