# Generated by Django 6.0.4 on 2026-09-15 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0076_snapshot_match_contract_version'),
        ('zelda_api', '0021_backfill_recommendation_vocabulary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityReportAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='entityverificationreport',
            name='checked_at',
            field=models.DateTimeField(blank=True, help_text='When public sources were consulted.', null=True),
        ),
        migrations.AddField(
            model_name='entityverificationreport',
            name='findings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='entityverificationreport',
            name='founder_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_verification_reports', to='matchmaking.application'),
        ),
        migrations.AddField(
            model_name='entityverificationreport',
            name='inputs_hash',
            field=models.CharField(blank=True, help_text='Fingerprint of the profile fields checked, so an edited profile gets a fresh check.', max_length=64),
        ),
        migrations.AddField(
            model_name='entityverificationreport',
            name='seller_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_verification_reports', to='matchmaking.sellerapplication'),
        ),
        migrations.AddField(
            model_name='entityverificationreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Checking'), ('complete', 'Complete')], default='complete', max_length=10),
        ),
        migrations.AlterField(
            model_name='entityverificationreport',
            name='document',
            field=models.ForeignKey(blank=True, help_text='The deck this check was run from, when there was one. The only link on reports made before business-level checks.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_verification_reports', to='zelda_api.documentsource'),
        ),
        migrations.AddConstraint(
            model_name='entityverificationreport',
            constraint=models.CheckConstraint(condition=models.Q(('founder_profile__isnull', True), ('seller_profile__isnull', True), _connector='OR'), name='entity_report_one_business_at_most'),
        ),
        migrations.AddConstraint(
            model_name='entityverificationreport',
            constraint=models.CheckConstraint(condition=models.Q(('founder_profile__isnull', False), ('seller_profile__isnull', False), ('document__isnull', False), _connector='OR'), name='entity_report_has_a_business_or_document'),
        ),
        migrations.AddField(
            model_name='entityreportaccessgrant',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='zelda_api.entityverificationreport'),
        ),
        migrations.AddField(
            model_name='entityreportaccessgrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_report_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='entityreportaccessgrant',
            constraint=models.UniqueConstraint(fields=('report', 'user'), name='entity_report_grant_once_per_user'),
        ),
    ]
