# Generated by Django 6.0.4 on 2026-09-19 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0024_sections_analyse_rather_than_advocate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('revenue', 'Revenue'), ('arr', 'Annual Recurring Revenue (ARR)'), ('customers', 'Customer Count'), ('growth_rate', 'Growth Rate (%)'), ('employees', 'Employee Count'), ('funding_raised', 'Funding Raised'), ('market_share', 'Market Share'), ('market_size', 'Total Addressable Market Size'), ('user_count', 'User Count'), ('engagement', 'Engagement Metric'), ('churn', 'Churn Rate'), ('team_size', 'Team Size'), ('office_locations', 'Office Locations'), ('countries', 'Countries Served'), ('other', 'Other Metric')], max_length=50)),
                ('original_evidence_state', models.CharField(max_length=20)),
                ('original_observed_text', models.TextField(blank=True)),
                ('reason', models.TextField(help_text='What the company says is wrong with the finding')),
                ('evidence_text', models.TextField(blank=True, help_text='Supporting detail the company supplied')),
                ('evidence_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Under review'), ('UPHELD', 'Upheld — the finding stands on the evidence reviewed'), ('CORRECTED', 'Corrected — the evidence warranted a change'), ('CLOSED_INSUFFICIENT', 'Closed — insufficient basis to change it'), ('WITHDRAWN', 'Withdrawn')], default='OPEN', max_length=20)),
                ('resolution_note', models.TextField(blank=True, help_text='Why staff decided what they decided')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finding_disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='zelda_api.truthdeltareport')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finding_disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report', 'status'], name='zelda_api_f_report__226aeb_idx')],
            },
        ),
    ]
