# Generated by Django 6.0.4 on 2026-09-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0025_finding_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='truthdeltareport',
            name='engine_version',
            field=models.CharField(default='unknown', help_text="The evidence semantics that produced this report; 'unknown' predates stamping.", max_length=32),
        ),
    ]
