# Generated by Django 6.0.4 on 2026-09-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0026_truthdeltareport_engine_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='observeddatapoint',
            name='registrant',
            field=models.CharField(blank=True, help_text='The registrant this figure was observed about, e.g. an SEC CIK.', max_length=32),
        ),
    ]
