# Generated by Django 6.0.4 on 2026-09-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0027_observeddatapoint_registrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsource',
            name='verification_error',
            field=models.TextField(blank=True, help_text='Technical cause of the last verification failure. Never shown to end users.'),
        ),
        migrations.AddField(
            model_name='documentsource',
            name='verification_failed_at',
            field=models.DateTimeField(blank=True, help_text='When Truth Delta verification last failed. Cleared by a successful run.', null=True),
        ),
    ]
