# Generated by Django 6.0.4 on 2026-10-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0028_document_verification_failure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimeddatapoint',
            name='text_excerpt',
            field=models.TextField(blank=True, help_text="The claim's own sentence, bounded to 300 characters. Never the source chunk: page_number and chunk_hash carry provenance."),
        ),
        migrations.AlterField(
            model_name='documentsource',
            name='status',
            field=models.CharField(choices=[('ingested', 'Ingested'), ('chunking', 'Chunking'), ('chunked', 'Chunked'), ('embedding', 'Embedding'), ('embedded', 'Embedded'), ('analyzing', 'Analyzing'), ('verifying', 'Verifying'), ('analyzed', 'Analyzed'), ('error', 'Error')], default='ingested', max_length=20),
        ),
    ]
