# Generated by Django 6.0.4 on 2026-10-04 03:00

from django.db import migrations, models

# Every existing row was written through may_establish, so the 'can_establish'
# default is already true of it. Its origin follows from its source.
ORIGINS = {'sec': 'sec_filing', 'crunchbase': 'third_party_database', 'news': 'news'}


def backfill_origin(apps, schema_editor):
    ObservedDatapoint = apps.get_model('zelda_api', 'ObservedDatapoint')
    for source_type, origin in ORIGINS.items():
        ObservedDatapoint.objects.filter(source__source_type=source_type, evidence_origin='').update(
            evidence_origin=origin)


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0030_bound_claimed_text_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='observeddatapoint',
            name='evidence_origin',
            field=models.CharField(blank=True, choices=[('sec_filing', 'SEC filing'), ('company_document', 'Company document'), ('company_website', 'Company website'), ('third_party_database', 'Third-party database'), ('linkedin_derived', 'LinkedIn-derived'), ('news', 'News')], max_length=32),
        ),
        migrations.AddField(
            model_name='observeddatapoint',
            name='role',
            field=models.CharField(choices=[('can_establish', 'Establishes'), ('can_corroborate', 'Corroborates'), ('informational_only', 'Informational only')], default='can_establish', help_text="The source's declared role for this category when the row was stored.", max_length=20),
        ),
        migrations.RunPython(backfill_origin, migrations.RunPython.noop),
    ]
