# Generated by Django 6.0.4 on 2026-10-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0031_observeddatapoint_role_and_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='observeddatapoint',
            name='provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='externaldatasource',
            name='source_type',
            field=models.CharField(choices=[('crunchbase', 'Crunchbase'), ('dataforb2b', 'DataForB2B'), ('linkedin', 'LinkedIn'), ('sec', 'SEC EDGAR'), ('web', 'Web Scraping'), ('news', 'News Articles'), ('domain', 'Domain WHOIS'), ('jobs', 'Job Boards'), ('news_api', 'News API'), ('corporate', 'Corporate Filings'), ('other', 'Other Source')], max_length=20),
        ),
    ]
