# Generated by Django 6.0.4 on 2026-10-04 08:09

from django.db import migrations, models

# Every vector ever stored came from EmbeddingEngine's hashing -- embed_text
# has never called a model -- but carried the field default
# "claude-3-5-sonnet". Which of the two hash schemes produced an old row is not
# recoverable, so it is named for what is known.
LEGACY_LABEL = 'hash-legacy'


def relabel(apps, schema_editor):
    DocumentChunk = apps.get_model('zelda_api', 'DocumentChunk')
    DocumentChunk.objects.filter(embedding_model__startswith='claude').update(embedding_model=LEGACY_LABEL)


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0032_observeddatapoint_provenance_dataforb2b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunPython(relabel, migrations.RunPython.noop),
    ]
