# Generated by Django 6.0.4 on 2026-10-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0033_honest_embedding_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='page_number',
            field=models.IntegerField(blank=True, default=None, help_text='Slide/page this chunk came from; null when unknown', null=True),
        ),
    ]
