# Generated by Django 6.0.4 on 2026-10-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0034_chunk_page_number_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsource',
            name='verification_no_claims_at',
            field=models.DateTimeField(blank=True, help_text='When Truth Delta last completed with no claims to verify. Cleared by a report or a failure.', null=True),
        ),
    ]
