# Generated by Django 6.0.9 on 2026-10-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0040_hide_misplaced_qibby_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimeddatapoint',
            name='currency',
            field=models.CharField(blank=True, help_text='Explicit monetary currency code; blank means unknown, including a bare $.', max_length=3),
        ),
        migrations.AddField(
            model_name='observeddatapoint',
            name='currency',
            field=models.CharField(blank=True, help_text="Currency explicitly supplied by this observation's source; blank means unknown.", max_length=3),
        ),
    ]
