# Generated by Django 6.0.4 on 2026-10-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0040_hide_misplaced_qibby_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimeddatapoint',
            name='ownership',
            field=models.CharField(blank=True, choices=[('named', 'Source sentence names the company'), ('implied', "Company's own document; no other owner named")], max_length=10),
        ),
    ]
