# Generated by Django 6.0.4 on 2026-10-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0042_claimeddatapoint_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimeddatapoint',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimeddatapoint',
            name='period_fiscal_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimeddatapoint',
            name='period_kind',
            field=models.CharField(blank=True, choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('ttm', 'Trailing twelve months'), ('run_rate', 'Run-rate'), ('cumulative', 'Cumulative')], max_length=12),
        ),
        migrations.AddField(
            model_name='observeddatapoint',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observeddatapoint',
            name='period_fiscal_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observeddatapoint',
            name='period_kind',
            field=models.CharField(blank=True, choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('ttm', 'Trailing twelve months'), ('run_rate', 'Run-rate'), ('cumulative', 'Cumulative')], max_length=12),
        ),
    ]
