# Generated by Django 6.0.4 on 2026-07-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('FOUNDER_PREMIUM', 'Founder Premium'), ('INVESTOR_PREMIUM', 'Investor Premium'), ('BUYER_PREMIUM', 'Buyer Premium')], max_length=20),
        ),
    ]
