# Generated by Django 6.0.4 on 2026-07-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('FOUNDER_PREMIUM', 'Founder Premium'), ('INVESTOR_PREMIUM', 'Investor Premium'), ('SELLER_PREMIUM', 'Seller Premium'), ('BUYER_PREMIUM', 'Buyer Premium'), ('INVESTOR_FIRM', 'Investor Firm')], max_length=20),
        ),
    ]
