# Generated by Django 6.0.4 on 2026-09-18 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SubscriptionConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=20)),
                ('price_usd', models.PositiveIntegerField()),
                ('interval', models.CharField(default='month', max_length=20)),
                ('terms_text', models.TextField(help_text='The exact disclosure shown when consent was given')),
                ('agreed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('billing_country', models.CharField(blank=True, max_length=2)),
                ('billing_state', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-agreed_at'],
                'indexes': [models.Index(fields=['user', '-agreed_at'], name='billing_sub_user_id_719c52_idx')],
            },
        ),
    ]
