# Generated by Django 6.0.4 on 2026-05-18 05:38

import django.db.models.deletion
import jobs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Company or Startup Name', max_length=255)),
                ('title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('description', models.TextField(help_text='Detailed job description and responsibilities')),
                ('location', models.CharField(default='Remote', help_text='e.g., San Diego, CA or Remote', max_length=150)),
                ('job_type', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('C', 'Contract'), ('I', 'Internship')], default='FT', max_length=2)),
                ('salary_range', models.CharField(blank=True, help_text='e.g., $120k - $150k', max_length=100, null=True)),
                ('equity_range', models.CharField(blank=True, help_text='e.g., 0.1% - 0.5%', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Premium paid placement boost')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=jobs.models.default_expiry)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('resume_attachment', models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/%d/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joblisting')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'applicant')},
            },
        ),
    ]
