# Generated by Django 6.0.4 on 2026-07-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
