# Generated by Django 6.0.4 on 2026-05-20 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=32, unique=True)),
                ('policy_type', models.CharField(choices=[('commercial_liability', 'Commercial General Liability'), ('key_person', 'Key Person Indemnity'), ('cyber_security', 'Cyber Risk & Data Breach'), ('property_asset', 'Commercial Property Coverage')], default='commercial_liability', max_length=30)),
                ('coverage_limit', models.DecimalField(decimal_places=2, help_text='Maximum aggregate payout limit.', max_digits=15)),
                ('deductible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium_annual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active / In Force'), ('underwriting', 'Pending Underwriting Review'), ('lapsed', 'Lapsed / Non-Payment')], default='underwriting', max_length=20)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insurance Policy',
                'verbose_name_plural': 'Insurance Policies',
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_reference', models.CharField(max_length=32, unique=True)),
                ('incident_description', models.TextField(help_text='Detailed summary of the loss or liability event.')),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('approved_payout_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('submitted', 'Claim Lodged / Pending Review'), ('investigating', 'Under Adjuster Investigation'), ('approved', 'Approved for Settlement payout'), ('denied', 'Claim Repudiated / Denied')], default='submitted', max_length=20)),
                ('ai_risk_assessment_flags', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance_api.insurancepolicy')),
            ],
            options={
                'verbose_name': 'Insurance Claim',
                'verbose_name_plural': 'Insurance Claims',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
