# Generated by Django 6.0.4 on 2026-05-20 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealershipShowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_city', models.CharField(max_length=150)),
                ('franchise_affiliations', models.JSONField(default=list, help_text='Array of brands sold, e.g., Tesla, BMW, Ford.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dealership Showroom',
                'verbose_name_plural': 'Dealership Showrooms',
            },
        ),
        migrations.CreateModel(
            name='VehicleAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN Number')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('ice', 'Internal Combustion Engine'), ('bev', 'Battery Electric Vehicle'), ('phev', 'Plug-in Hybrid Electric Vehicle')], default='ice', max_length=10)),
                ('base_msrp', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='MSRP Price')),
                ('status', models.CharField(choices=[('available', 'In Showroom Lot'), ('reserved', 'Deposit Placed'), ('sold', 'Delivered to Customer')], default='available', max_length=15)),
                ('extracted_spec_matrix', models.JSONField(blank=True, default=dict)),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='automotive_api.dealershipshowroom')),
            ],
            options={
                'verbose_name': 'Vehicle Asset',
                'verbose_name_plural': 'Vehicle Assets',
            },
        ),
        migrations.CreateModel(
            name='TestDriveBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('no_show', 'No Show / Cancelled')], default='scheduled', max_length=15)),
                ('confirmation_token', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automotive_bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to='automotive_api.vehicleasset')),
            ],
            options={
                'verbose_name': 'Test Drive Booking',
                'verbose_name_plural': 'Test Drive Bookings',
                'ordering': ['-scheduled_timestamp'],
            },
        ),
    ]
