# Generated by Django 6.0.4 on 2026-05-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automotive_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testdrivebooking',
            options={'verbose_name': 'Test Drive Booking', 'verbose_name_plural': 'Test Drive Bookings'},
        ),
        migrations.AddField(
            model_name='testdrivebooking',
            name='idempotency_key',
            field=models.UUIDField(blank=True, help_text='Unique key generated by the frontend to prevent double-booking.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='testdrivebooking',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp after which the car status reverts to 'available' if not completed.", null=True),
        ),
    ]
