# Generated by Django 6.0.4 on 2026-05-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_code', models.CharField(help_text='Unique facility identifier (e.g., WH-SD-01)', max_length=50, unique=True)),
                ('location_city', models.CharField(max_length=150)),
                ('total_cubic_capacity_meters', models.FloatField(default=1000.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Warehouse Node',
                'verbose_name_plural': 'Warehouse Nodes',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU Stock Keeping Unit')),
                ('name', models.CharField(max_length=255)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('reorder_threshold', models.IntegerField(default=10, help_text='Triggers safety stock warnings when inventory drops below this number.')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='logistics_api.warehousenode')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
            },
        ),
        migrations.CreateModel(
            name='FreightShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(choices=[('inbound', 'Inbound Supplier Restock'), ('outbound', 'Outbound Client Fulfillment')], default='outbound', max_length=15)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('carrier', models.CharField(choices=[('fedex', 'FedEx Freight'), ('ups', 'UPS Supply Chain'), ('dhl', 'DHL Global Forwarding'), ('freight_forwarder', 'Private Third-Party Logistics (3PL)')], default='fedex', max_length=30)),
                ('origin_facility', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('manifest_created', 'Manifest Staged'), ('transit', 'In Transit across Nodes'), ('delivered', 'Delivered & Count Ingested'), ('exception', 'Customs / Transit Delay Exception')], default='manifest_created', max_length=20)),
                ('zelda_logistics_telemetry', models.JSONField(blank=True, default=dict, help_text='Stores dynamic route optimization data and predictive arrival variance calculations.')),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('destination_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_freight', to='logistics_api.warehousenode')),
            ],
            options={
                'verbose_name': 'Freight Shipment',
                'verbose_name_plural': 'Freight Shipments',
                'ordering': ['-estimated_delivery'],
            },
        ),
    ]
