# Generated by Django 6.0.4 on 2026-05-20 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_city', models.CharField(max_length=100)),
                ('star_rating', models.FloatField(default=0.0)),
                ('extracted_amenity_matrix', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hotel Property',
                'verbose_name_plural': 'Hotel Properties',
            },
        ),
        migrations.CreateModel(
            name='RoomInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('room_type', models.CharField(choices=[('standard', 'Standard King/Queen'), ('deluxe', 'Deluxe Suite'), ('penthouse', 'Executive Penthouse')], default='standard', max_length=20)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_currently_vacant', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel_api.hotelproperty')),
            ],
            options={
                'verbose_name': 'Room Inventory Node',
                'verbose_name_plural': 'Room Inventory Nodes',
            },
        ),
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('total_stay_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('booking_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('cancelled', 'Cancelled')], default='confirmed', max_length=15)),
                ('confirmation_hash', models.CharField(max_length=64, unique=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to=settings.AUTH_USER_MODEL)),
                ('room_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_history', to='hotel_api.roominventory')),
            ],
            options={
                'verbose_name': 'Guest Reservation',
                'verbose_name_plural': 'Guest Reservations',
            },
        ),
    ]
