# Generated by Django 6.0.4 on 2026-06-18 06:56

import django.db.models.deletion
import zelda_api.protocol
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zelda_api', '0002_remove_joblisting_posted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('pitch_deck', 'Pitch Deck'), ('financial_model', 'Financial Model'), ('business_plan', 'Business Plan'), ('whitepaper', 'Whitepaper'), ('research', 'Research Report'), ('portfolio', 'Investor Portfolio'), ('other', 'Other')], default='pitch_deck', max_length=20)),
                ('source_entity', models.CharField(help_text='Founder name, investor name, or source', max_length=255)),
                ('raw_text_preview', models.TextField(blank=True, help_text='First 1000 chars for reference')),
                ('total_pages', models.IntegerField(default=0)),
                ('total_word_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ingested', 'Ingested'), ('chunking', 'Chunking'), ('chunked', 'Chunked'), ('embedding', 'Embedding'), ('embedded', 'Embedded'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('error', 'Error')], default='ingested', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0, help_text='0.0-1.0 overall analysis confidence')),
                ('intelligence_rank', models.IntegerField(default=0, help_text='Ranking by quality/relevance')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zelda_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Source',
                'verbose_name_plural': 'Document Sources',
                'ordering': ['-created_at'],
            },
            bases=(zelda_api.protocol.FoundryStandardMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(help_text='Order in the document (0-indexed)')),
                ('page_number', models.IntegerField(default=0, help_text='Page this chunk came from')),
                ('section_title', models.CharField(blank=True, help_text="e.g., 'Problem Statement', 'Market Size'", max_length=255)),
                ('raw_text', models.TextField(help_text='The actual text chunk')),
                ('token_count', models.IntegerField(help_text='Approximate token count for this chunk')),
                ('embedding_vector', models.JSONField(blank=True, help_text='Vector embedding (list of floats)', null=True)),
                ('embedding_model', models.CharField(blank=True, default='claude-3-5-sonnet', max_length=100)),
                ('is_key_insight', models.BooleanField(default=False, help_text='Marked as particularly important')),
                ('relevance_score', models.FloatField(default=0.5, help_text='0.0-1.0 relevance for the document topic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='zelda_api.documentsource')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'ordering': ['document', 'chunk_index'],
            },
            bases=(zelda_api.protocol.FoundryStandardMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IntelligenceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('metric', 'Metric Extraction'), ('trend', 'Trend Analysis'), ('risk', 'Risk Assessment'), ('opportunity', 'Opportunity'), ('statement', 'Key Statement'), ('assumption', 'Assumption'), ('recommendation', 'Recommendation'), ('other', 'Other')], default='statement', max_length=20)),
                ('category', models.CharField(help_text="e.g., 'TAM', 'Team Size', 'Risk'", max_length=100)),
                ('insight_text', models.TextField(help_text='The actual insight extracted')),
                ('confidence_score', models.FloatField(default=0.7, help_text='0.0-1.0 confidence in this insight')),
                ('source_attribution', models.CharField(blank=True, help_text="e.g., 'Slide 5', 'Page 3, paragraph 2'", max_length=255)),
                ('metric_value', models.CharField(blank=True, help_text="e.g., '$5M', '50 employees'", max_length=100)),
                ('metric_unit', models.CharField(blank=True, help_text="e.g., 'USD', 'headcount'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='zelda_api.documentsource')),
                ('source_chunks', models.ManyToManyField(help_text='Chunks this insight was derived from', related_name='insights', to='zelda_api.documentchunk')),
            ],
            options={
                'verbose_name': 'Intelligence Insight',
                'verbose_name_plural': 'Intelligence Insights',
                'ordering': ['-confidence_score', '-created_at'],
            },
            bases=(zelda_api.protocol.FoundryStandardMixin, models.Model),
        ),
        migrations.CreateModel(
            name='IntelligenceMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.TextField(help_text='High-level overview with key metrics')),
                ('problem_solution', models.TextField(blank=True, help_text='Problem statement and proposed solution')),
                ('market_analysis', models.TextField(blank=True, help_text='TAM, SAM, SOM with sources')),
                ('team_assessment', models.TextField(blank=True, help_text='Team experience, background, gaps')),
                ('financial_analysis', models.TextField(blank=True, help_text='Revenue, burn, runway, unit economics')),
                ('risk_assessment', models.TextField(blank=True, help_text='Key risks and mitigation strategies')),
                ('investment_thesis', models.TextField(help_text='Why this is investable')),
                ('retrieved_context', models.TextField(help_text='Raw context assembled from retrieval')),
                ('completeness_score', models.FloatField(default=0.0, help_text='0.0-1.0 memo completeness')),
                ('citations_count', models.IntegerField(default=0, help_text='Number of source citations')),
                ('recommendation', models.CharField(choices=[('strong_pass', 'Strong Pass'), ('pass', 'Pass'), ('consider', 'Consider'), ('interview', 'Schedule Interview'), ('strong_interest', 'Strong Interest')], default='consider', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memo', to='zelda_api.documentsource')),
                ('insights_used', models.ManyToManyField(related_name='memos', to='zelda_api.intelligenceinsight')),
            ],
            options={
                'verbose_name': 'Intelligence Memo',
                'verbose_name_plural': 'Intelligence Memos',
                'ordering': ['-created_at'],
            },
            bases=(zelda_api.protocol.FoundryStandardMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='documentsource',
            index=models.Index(fields=['status', '-created_at'], name='zelda_api_d_status_a64ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsource',
            index=models.Index(fields=['source_entity'], name='zelda_api_d_source__b03304_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='zelda_api_d_documen_8a6cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['is_key_insight'], name='zelda_api_d_is_key__e619e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_index')},
        ),
        migrations.AddIndex(
            model_name='intelligenceinsight',
            index=models.Index(fields=['document', 'insight_type'], name='zelda_api_i_documen_b10072_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligenceinsight',
            index=models.Index(fields=['category'], name='zelda_api_i_categor_1b80a1_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligenceinsight',
            index=models.Index(fields=['-confidence_score'], name='zelda_api_i_confide_dccee6_idx'),
        ),
    ]
