"""
Shared legal disclaimer text for every AI-generated intelligence surface
(Intelligence Memo, Truth Delta, IC Memo, Valuation) — one string so the
wording can't drift between report types as they're edited independently.
"""

DUE_DILIGENCE_DISCLAIMER = (
    "This report was generated by Zelda AI to support preliminary due diligence. It is not an "
    "audited financial statement, does not constitute investment, legal, or tax advice, and is "
    "not a binding representation by Interlink Foundry. Investors are solely responsible for "
    "conducting their own independent due diligence — including verification of all claims, "
    "financials, and legal standing — before making any investment decision."
)
