"""
Zelda states evidence. It never tells anyone to invest, pass, buy, sell or hold.

The memo used to store a verdict -- STRONG_INVEST, INVEST, NEEDS_REVIEW or
PASS -- generated by Claude and shown to paying investor subscribers, on the
same page as a disclaimer saying the report "does not constitute investment,
legal, or tax advice". One of those had to go.

Interlink Foundry is a neutral marketplace: it reports what a company states,
what evidence supports it, and what real people did on the platform, and the
reader decides. So the verdict is gone at the source -- the field itself, not
its label -- and an evidence level took its place.

"Investment Readiness" became "Information Readiness" for the same reason: it
measures how complete the information is, not whether the company is worth
investing in.

The last test here is a standing guard. It scans production code and templates
for the prohibited vocabulary, so nobody can reintroduce an equivalent surface
later. Migrations are exempt: they are history, and historical rows legitimately
contain the old values.
"""
import re
from pathlib import Path

from django.conf import settings
from django.contrib.auth import get_user_model
from django.test import SimpleTestCase, TestCase
from django.urls import reverse
from unittest import mock

from matchmaking.models import Application, Connection, InvestorApplication
from matchmaking.tests import _mock_embedding_generation

from .vector_models import DocumentSource, IntelligenceMemo

User = get_user_model()

# Whole values and phrases, never bare "invest" -- "investment thesis" and
# "investment memo" are legitimate, and a substring match would fail on them.
FORBIDDEN_TOKENS = (
    'STRONG_INVEST',
    'NEEDS_REVIEW',
    "'INVEST'",
    '"INVEST"',
    "'PASS'",
    '"PASS"',
    'Strong Invest',
    'should invest',
    'do not invest',
    'recommended investment',
    'good investment',
    'bad investment',
)


class EvidenceLevelReplacesTheVerdictTests(TestCase):

    def test_the_memo_no_longer_has_a_recommendation_field(self):
        field_names = {f.name for f in IntelligenceMemo._meta.get_fields()}
        self.assertNotIn('recommendation', field_names)
        self.assertIn('evidence_level', field_names)

    def test_no_evidence_level_tells_anyone_what_to_do(self):
        field = IntelligenceMemo._meta.get_field('evidence_level')
        self.assertTrue(field.choices)
        for value, label in field.choices:
            with self.subTest(value=value):
                for token in FORBIDDEN_TOKENS:
                    self.assertNotIn(token.strip('\'"'), value)
                    self.assertNotIn(token.strip('\'"').lower(), label.lower())

    def test_an_unclassified_memo_is_the_default(self):
        self.assertEqual(IntelligenceMemo._meta.get_field('evidence_level').default, 'NOT_CLASSIFIED')

    def test_readiness_is_about_information_not_investment(self):
        field_names = {f.name for f in IntelligenceMemo._meta.get_fields()}
        self.assertIn('information_readiness', field_names)
        self.assertNotIn('investment_readiness', field_names)


class MemoPromptTests(SimpleTestCase):

    def test_the_prompt_asks_for_an_evidence_level(self):
        from .intelligence_pipeline import EVIDENCE_LEVEL_INSTRUCTION, MEMO_JSON_KEYS
        self.assertIn('evidence_level', MEMO_JSON_KEYS)
        self.assertNotIn('recommendation', MEMO_JSON_KEYS)
        for token in FORBIDDEN_TOKENS:
            self.assertNotIn(token, EVIDENCE_LEVEL_INSTRUCTION)

    def test_the_fallback_returns_an_evidence_level(self):
        from .intelligence_pipeline import intelligence_pipeline
        levels = {
            intelligence_pipeline._determine_evidence_level([], confidence)
            for confidence in (95, 70, 50, 10)
        }
        valid = {value for value, _ in IntelligenceMemo._meta.get_field('evidence_level').choices}
        self.assertTrue(levels <= valid)
        self.assertEqual(len(levels), 4)


class ICMemoPageTests(TestCase):
    """The page an investor actually reads."""

    def setUp(self):
        _mock_embedding_generation(self)
        self.founder_user = User.objects.create_user('nia_founder', password='x')
        self.founder = Application.objects.create(
            user=self.founder_user, company_name='NIACo', founder_name='F', email='nia@t.test',
            description='d', sector='SaaS', stage='Seed',
        )
        self.staff = User.objects.create_user('nia_staff', password='x', is_staff=True)
        self.doc = DocumentSource.objects.create(
            uploaded_by=self.founder_user, filename='deck.pdf', source_entity='NIACo',
            document_type='pitch_deck', status='analyzed',
            raw_text_full='NIACo builds scheduling software. Revenue $400k.',
        )
        IntelligenceMemo.objects.create(
            document=self.doc, executive_summary='A summary.',
            evidence_level='PARTLY_EVIDENCED',
            information_readiness='Score: 62/100\nSome sections are missing.',
            completeness_score=0.7, citations_count=3,
        )
        self.url = reverse('zelda_api:ic_memo', args=[self.doc.id])

    def _page(self):
        self.client.force_login(self.staff)
        response = self.client.get(self.url)
        self.assertEqual(response.status_code, 200)
        return response.content.decode()

    def test_the_page_states_evidence_not_a_verdict(self):
        html = self._page()
        # Positive control: this is the memo page.
        self.assertIn('A summary.', html)
        self.assertIn('Partly evidenced', html)
        for token in ('Strong Invest', '✗ Pass', 'Recommendation'):
            with self.subTest(token=token):
                self.assertNotIn(token, html)

    def test_readiness_is_labelled_and_defined_as_information(self):
        html = self._page()
        self.assertIn('Information Readiness', html)
        self.assertNotIn('Investment Readiness', html)
        # The definition has to say what it is not.
        self.assertRegex(html, r'not an assessment of whether')


class NoAdvisoryVocabularyAnywhereTests(SimpleTestCase):
    """
    A standing guard, not a one-off check: production code and templates must
    stay free of action-recommendation vocabulary. Migrations are exempt --
    they record history, including the old values.
    """

    def test_production_code_and_templates_are_free_of_it(self):
        root = Path(settings.BASE_DIR)
        searched, offenders = 0, []
        for path in list(root.glob('*/[!.]*.py')) + list((root / 'templates').rglob('*.html')):
            parts = path.parts
            if 'migrations' in parts or 'venv' in parts or 'node_modules' in parts:
                continue
            if path.name.startswith('test') or path.name == 'tests.py':
                continue
            searched += 1
            text = path.read_text(encoding='utf-8', errors='ignore')
            for token in FORBIDDEN_TOKENS:
                if token in text:
                    offenders.append(f'{path.relative_to(root)}: {token}')
        # Positive control: the scan actually reached the files it claims to.
        self.assertGreater(searched, 50)
        self.assertEqual(offenders, [], 'advisory vocabulary found in production code')
