# Generated by Django 6.0.4 on 2026-05-15 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
                ('current_revenue', models.CharField(blank=True, max_length=50, null=True)),
                ('years_in_business', models.PositiveIntegerField(blank=True, null=True)),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
                ('raising_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('prior_amount_raised', models.CharField(blank=True, max_length=50, null=True)),
                ('reason_for_capital', models.TextField(blank=True, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('description_vector', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_founder_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('investment_focus', models.TextField()),
                ('investment_stage', models.CharField(max_length=255)),
                ('investment_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('focus_vector', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Intro Sent'), ('DECLINED', 'Declined'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20)),
                ('investor_note', models.TextField(blank=True, help_text='Note to admin or founder.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_intros', to='matchmaking.application')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_intros', to='matchmaking.investorapplication')),
            ],
            options={
                'unique_together': {('investor', 'founder')},
            },
        ),
        migrations.CreateModel(
            name='AIMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('reasons', models.JSONField(default=list)),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_matches', to='matchmaking.application')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_matches', to='matchmaking.investorapplication')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('investor', 'founder')},
            },
        ),
        migrations.CreateModel(
            name='MatchFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.application')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.investorapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'application', 'investor')},
            },
        ),
    ]
