# Generated by Django 6.0.4 on 2026-05-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this startup has been vetted by the brokerage team to appear in investor matching.'),
        ),
        migrations.AddField(
            model_name='application',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated fallback tags for strict keyword matching.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='investor_note',
            field=models.TextField(blank=True, help_text='Optional note provided by the investor to facilitate the intro request.'),
        ),
    ]
