# Generated by Django 6.0.4 on 2026-05-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_application_is_verified_application_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='file_search_store_id',
            field=models.CharField(blank=True, help_text='The native Gemini managed vector store identifier used for grounding checks.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='pitch_deck',
            field=models.FileField(blank=True, help_text='Founder pitch deck file (PDF) used for multimodal Gemini analysis.', null=True, upload_to='pitch_decks/'),
        ),
    ]
