# Generated by Django 6.0.4 on 2026-05-17 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_application_file_search_store_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Founder LinkedIn Profile'),
        ),
        migrations.AddField(
            model_name='application',
            name='location',
            field=models.CharField(blank=True, help_text='HQ Operating Location (e.g., San Francisco, CA or London, UK)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Investor LinkedIn Profile'),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='location',
            field=models.CharField(blank=True, help_text='Operating Hub Base (e.g., New York, NY or Toronto, ON)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aimatch',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Allows users to archive this match configuration from active view feeds.'),
        ),
        migrations.AlterField(
            model_name='aimatch',
            name='reasons',
            field=models.JSONField(default=list, help_text='Array listing specific context justifications generated by Gemini.'),
        ),
        migrations.AlterField(
            model_name='aimatch',
            name='score',
            field=models.FloatField(help_text='Calculated match index score spanning 0.0 to 100.0'),
        ),
        migrations.AlterField(
            model_name='application',
            name='company_size',
            field=models.CharField(blank=True, help_text='e.g., 1-10, 11-50 employees', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='company_website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='current_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(help_text='One-sentence pitch or short technical summary.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description_vector',
            field=models.JSONField(blank=True, help_text='System multi-modal float embedding matrix array.', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='file_search_store_id',
            field=models.CharField(blank=True, help_text='The native Gemini managed vector file identifier used for grounding queries.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this startup has been vetted by the team to appear in general investor bulletin boards.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated tokens for matching algorithms (e.g., saas, b2b, ai).', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='pitch_deck',
            field=models.FileField(blank=True, help_text='Founder pitch deck file (PDF) used for multimodal Gemini analysis.', null=True, upload_to='pitch_decks/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='prior_amount_raised',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='raising_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='sector',
            field=models.CharField(blank=True, help_text='Primary vertical index (e.g., SaaS, FinTech, AI)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(blank=True, help_text='Current fundraising round stage (e.g., Pre-Seed, Seed)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='years_in_business',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='investor_note',
            field=models.TextField(blank=True, help_text='Optional note provided by the investor to facilitate the introduction.'),
        ),
        migrations.AlterField(
            model_name='investorapplication',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Firm / Fund Name'),
        ),
        migrations.AlterField(
            model_name='investorapplication',
            name='focus_vector',
            field=models.JSONField(blank=True, help_text='System vector embedding cache array representing investment thesis strategy.', null=True),
        ),
        migrations.AlterField(
            model_name='investorapplication',
            name='investment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target ticket check size allocation metric deployment limit.', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='investorapplication',
            name='investment_focus',
            field=models.TextField(help_text='Detailed summary of targeted industry criteria or fund investment thesis.'),
        ),
        migrations.AlterField(
            model_name='investorapplication',
            name='investment_stage',
            field=models.CharField(help_text='Target stages (e.g., Seed, Series A)', max_length=255),
        ),
        migrations.AlterField(
            model_name='investorapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matchfeedback',
            name='feedback_text',
            field=models.TextField(blank=True, help_text='User descriptive commentary explaining vote rationale.', null=True),
        ),
    ]
