# Generated by Django 6.0.4 on 2026-05-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0004_application_linkedin_url_application_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorapplication',
            name='investment_amount',
            field=models.CharField(blank=True, help_text='Target ticket check size range metric deployment limit (e.g., 250,000-500,000).', max_length=255, null=True),
        ),
    ]
