# Generated by Django 6.0.4 on 2026-05-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0005_alter_investorapplication_investment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='current_revenue',
            field=models.CharField(blank=True, default='0', help_text='Annual or Monthly Recurring Revenue breakdown metric.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='prior_amount_raised',
            field=models.CharField(blank=True, default='0', help_text='Aggregate capital raised previously.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='raising_amount',
            field=models.CharField(blank=True, help_text='Target fundraising target metric (e.g., 200,000 or 1.5M).', max_length=100, null=True),
        ),
    ]
