# Generated by Django 6.0.4 on 2026-05-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0006_alter_application_current_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorapplication',
            name='target_distance_range',
            field=models.CharField(default='GLOBAL', help_text='Target radial allocation limit (e.g., Local, Regional, National, GLOBAL)', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='years_in_business',
            field=models.CharField(blank=True, help_text='e.g., Less than 1 year, 1–2 years, 3–5 years', max_length=100, null=True),
        ),
    ]
