# Generated by Django 6.0.4 on 2026-05-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0007_investorapplication_target_distance_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorapplication',
            name='portfolio_raw_text',
            field=models.TextField(blank=True, help_text='Scraped textual layout telemetry from historical fund portfolio data uploads.', null=True),
        ),
    ]
