# Generated by Django 6.0.4 on 2026-05-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0008_investorapplication_portfolio_raw_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Hides your startup profile from the global search directory and the public board.'),
        ),
    ]
