# Generated by Django 6.0.4 on 2026-05-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0009_application_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorapplication',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Incognito Mode: Hides your profile from public visibility boards, global metrics grids, and Zelda AI.'),
        ),
    ]
