# Generated by Django 6.0.4 on 2026-05-29 12:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0010_investorapplication_is_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimatch',
            options={'ordering': ['-score'], 'verbose_name': 'AI Match Log', 'verbose_name_plural': 'AI Match Logs'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'Founder Application', 'verbose_name_plural': 'Founder Applications'},
        ),
        migrations.AlterModelOptions(
            name='connection',
            options={'verbose_name': 'Platform Connection', 'verbose_name_plural': 'Platform Connections'},
        ),
        migrations.AlterModelOptions(
            name='investorapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Investor Profile', 'verbose_name_plural': 'Investor Profiles'},
        ),
        migrations.AlterModelOptions(
            name='matchfeedback',
            options={'verbose_name': 'Match Feedback', 'verbose_name_plural': 'Match Feedbacks'},
        ),
        migrations.RenameField(
            model_name='aimatch',
            old_name='founder',
            new_name='application',
        ),
        migrations.AlterUniqueTogether(
            name='aimatch',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='matchfeedback',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='application',
            name='file_search_store_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='application',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='application',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='application',
            name='location',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='investor_note',
        ),
        migrations.RemoveField(
            model_name='investorapplication',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='investorapplication',
            name='location',
        ),
        migrations.RemoveField(
            model_name='investorapplication',
            name='portfolio_raw_text',
        ),
        migrations.RemoveField(
            model_name='investorapplication',
            name='target_distance_range',
        ),
        migrations.AlterField(
            model_name='aimatch',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='company_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='current_revenue',
            field=models.IntegerField(default=0, help_text='Numeric value for search filtering'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(verbose_name='Executive Summary'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description_vector',
            field=models.JSONField(blank=True, help_text='Stores embeddings array', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Enable incognito mode to omit your application from global filters and automated AI indexing.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='pitch_deck',
            field=models.FileField(blank=True, null=True, upload_to='pitch_decks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'pptx', 'ppt'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='prior_amount_raised',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='raising_amount',
            field=models.IntegerField(default=0, help_text='Numeric value for search filtering'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sector',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(default='Seed', max_length=100, verbose_name='Funding Stage'),
        ),
        migrations.AlterField(
            model_name='application',
            name='years_in_business',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='matchmaking.application'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='matchmaking.investorapplication'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='investorapplication',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='investorapplication',
            name='focus_vector',
            field=models.JSONField(blank=True, help_text='Stores embeddings array', null=True),
        ),
        migrations.AlterField(
            model_name='investorapplication',
            name='investment_amount',
            field=models.CharField(default='Unspecified', max_length=100, verbose_name='Target Ticket Size'),
        ),
        migrations.AlterField(
            model_name='investorapplication',
            name='investment_focus',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='investorapplication',
            name='investment_stage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='investorapplication',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matchfeedback',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='matchmaking.application'),
        ),
        migrations.AlterField(
            model_name='matchfeedback',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='matchmaking.investorapplication'),
        ),
        migrations.AlterField(
            model_name='matchfeedback',
            name='vote',
            field=models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')]),
        ),
        migrations.RemoveField(
            model_name='aimatch',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='aimatch',
            name='reasons',
        ),
        migrations.RemoveField(
            model_name='matchfeedback',
            name='feedback_text',
        ),
    ]
