# Generated by Django 6.0.4 on 2026-06-02 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0011_alter_aimatch_options_alter_application_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_requests', to='matchmaking.application')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_requests', to='matchmaking.investorapplication')),
            ],
        ),
    ]
