# Generated by Django 6.0.4 on 2026-06-06 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0012_connectionrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.RemoveField(
            model_name='application',
            name='description_vector',
        ),
        migrations.AddField(
            model_name='application',
            name='monthly_burn_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='company_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='current_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='pitch_deck',
            field=models.FileField(blank=True, null=True, upload_to='decks/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'pptx'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='prior_amount_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='application',
            name='raising_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(default='Seed', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='years_in_business',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
