# Generated by Django 6.0.4 on 2026-06-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0013_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='runway_months',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='application',
            name='zelda_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
