# Generated by Django 6.0.4 on 2026-06-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0014_application_runway_months_application_zelda_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
