# Generated by Django 6.0.4 on 2026-06-13 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pitch_video',
            field=models.FileField(blank=True, help_text='Upload a short 1-3 minute video pitch (MP4, MOV, WEBM).', null=True, upload_to='pitch_videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm'])]),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
