# Generated by Django 6.0.4 on 2026-06-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0020_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='allow_direct_messages',
            field=models.BooleanField(default=False, help_text='If True, verified users can bypass the matchmaking radar to initiate a Deal Room chat.'),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='allow_direct_messages',
            field=models.BooleanField(default=False, help_text='If True, verified users can bypass the matchmaking radar to initiate a Deal Room chat.'),
        ),
    ]
