# Generated by Django 6.0.4 on 2026-06-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0021_application_allow_direct_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimatch',
            name='confidence_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='aimatch',
            name='match_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='description_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='geography',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='zelda_last_analysis',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='zelda_risk_assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='zelda_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='focus_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='investment_thesis_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='last_portfolio_analysis',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='portfolio_raw_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aimatch',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
