# Generated by Django 6.0.4 on 2026-06-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0022_aimatch_confidence_score_aimatch_match_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimatch',
            name='geography',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
