# Generated by Django 6.0.4 on 2026-07-02 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0024_application_linkedin_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorInterestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'Profile View'), ('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down'), ('analyze', 'Analyzed with Zelda'), ('memo_view', 'Viewed Intelligence Memo'), ('truth_delta_view', 'Viewed Truth Delta'), ('intro_request', 'Requested Introduction'), ('message_sent', 'Sent Direct Message')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_events', to='matchmaking.application')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['founder', '-created_at'], name='matchmaking_founder_885c94_idx'), models.Index(fields=['investor', '-created_at'], name='matchmaking_investo_dfdc75_idx'), models.Index(fields=['event_type'], name='matchmaking_event_t_fdd74d_idx')],
            },
        ),
    ]
