# Generated by Django 6.0.4 on 2026-07-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0025_investorinterestevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='vector_fields_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
