# Generated by Django 6.0.4 on 2026-07-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0026_application_vector_fields_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='denial_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='review_status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending Review'), ('DENIED', 'Denied')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='connection',
            name='initiated_by',
            field=models.CharField(choices=[('INVESTOR', 'Investor'), ('FOUNDER', 'Founder')], default='INVESTOR', max_length=20),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='denial_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Premium tier: bypasses the daily outreach cap.'),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='review_status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending Review'), ('DENIED', 'Denied')], default='APPROVED', max_length=20),
        ),
    ]
