# Generated by Django 6.0.4 on 2026-07-03 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0027_application_denial_reason_application_is_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchDeckViewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_session_id', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_view_sessions', to='matchmaking.application')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('founder', 'viewer', 'client_session_id')},
            },
        ),
        migrations.CreateModel(
            name='PitchDeckSlideTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.PositiveIntegerField()),
                ('duration_seconds', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_times', to='matchmaking.pitchdeckviewsession')),
            ],
        ),
    ]
