# Generated by Django 6.0.4 on 2026-07-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0028_pitchdeckviewsession_pitchdeckslidetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundraisingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=255)),
                ('firm_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('stage', models.CharField(choices=[('LEADS', 'Leads'), ('CONTACTED', 'Contacted'), ('MEETING_BOOKED', 'Meeting Booked'), ('DUE_DILIGENCE', 'Due Diligence'), ('TERM_SHEET', 'Term Sheet')], default='LEADS', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundraising_leads', to='matchmaking.application')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
