# Generated by Django 6.0.4 on 2026-07-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0029_fundraisinglead'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorapplication',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
