# Generated by Django 6.0.4 on 2026-07-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0030_investorapplication_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorinterestevent',
            name='event_type',
            field=models.CharField(choices=[('view', 'Profile View'), ('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down'), ('analyze', 'Analyzed with Zelda'), ('memo_view', 'Viewed Intelligence Memo'), ('truth_delta_view', 'Viewed Truth Delta'), ('intro_request', 'Requested Introduction'), ('message_sent', 'Sent Direct Message'), ('funded', 'Deal Funded')], max_length=20),
        ),
    ]
