# Generated by Django 6.0.4 on 2026-07-03 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0031_alter_investorinterestevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('revenue', 'Revenue Milestone'), ('customers', 'Customer Milestone'), ('product_launch', 'Product Launch'), ('hiring', 'Hiring Update'), ('funding', 'Funding Update'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='matchmaking.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
