# Generated by Django 6.0.4 on 2026-07-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0032_foundermilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='needs_attention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connection',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
