# Generated by Django 6.0.4 on 2026-07-04 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0034_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorPredictionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_score', models.FloatField()),
                ('runner_up_founders', models.JSONField(blank=True, default=list, help_text='Top 5 [{founder_id, score}] at snapshot time')),
                ('snapshot_telemetry', models.JSONField(blank=True, default=dict, help_text='InvestorInterestEvent counts + portfolio/vector presence at snapshot time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A — Predicted Correctly'), ('B', 'B — Sector/Stage/Geo Sound, Investor Deviated'), ('C', 'C — Partial Signal Match'), ('D', 'D — Weak Signal Match'), ('F', 'F — Missed Entirely')], max_length=1, null=True)),
                ('grade_score', models.FloatField(blank=True, help_text='0-100 raw score before A-F bucketing', null=True)),
                ('grade_explanation', models.TextField(blank=True)),
                ('actual_funded_founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_prediction_snapshots', to='matchmaking.application')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_snapshots', to='matchmaking.investorapplication')),
                ('predicted_founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_by_snapshots', to='matchmaking.application')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['investor', '-created_at'], name='matchmaking_investo_8b5aaf_idx'), models.Index(fields=['is_resolved'], name='matchmaking_is_reso_01775a_idx')],
            },
        ),
    ]
