# Generated by Django 6.0.4 on 2026-07-04 03:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0035_investorpredictionsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('acquisition_thesis', models.TextField(help_text='What kind of businesses are you looking to acquire?')),
                ('focus_vector', models.JSONField(blank=True, null=True)),
                ('target_revenue_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('target_revenue_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('target_ebitda_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('target_ebitda_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('preferred_deal_structure', models.CharField(choices=[('ASSET_SALE', 'Asset Sale'), ('STOCK_SALE', 'Stock Sale'), ('MERGER', 'Merger'), ('OPEN', 'Open to Either'), ('NO_PREFERENCE', 'No Preference')], default='NO_PREFERENCE', max_length=20)),
                ('is_private', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False, help_text='Premium tier: bypasses the daily outreach cap.')),
                ('review_status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending Review'), ('DENIED', 'Denied')], default='APPROVED', max_length=20)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer (Acquirer) Profile',
                'verbose_name_plural': 'Buyer (Acquirer) Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_website', models.URLField(blank=True, max_length=500, null=True)),
                ('seller_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(verbose_name='Business Overview')),
                ('description_vector', models.JSONField(blank=True, null=True)),
                ('industry', models.CharField(default='Other', max_length=100)),
                ('geography', models.CharField(blank=True, max_length=255, null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('asking_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deal_structure', models.CharField(choices=[('ASSET_SALE', 'Asset Sale'), ('STOCK_SALE', 'Stock Sale'), ('MERGER', 'Merger'), ('OPEN', 'Open to Either')], default='OPEN', max_length=20)),
                ('team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('years_in_business', models.PositiveIntegerField(default=0)),
                ('reason_for_sale', models.TextField(blank=True, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('cim_document', models.FileField(blank=True, help_text='Confidential Information Memorandum — the standard M&A teaser/info packet.', null=True, upload_to='cim_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'pptx'])])),
                ('is_private', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending Review'), ('DENIED', 'Denied')], default='APPROVED', max_length=20)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vector_fields_updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_feedback', to='matchmaking.buyerapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_feedback', to='matchmaking.sellerapplication')),
            ],
            options={
                'verbose_name': 'Deal Feedback',
                'verbose_name_plural': 'Deal Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='AcquisitionInterestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'Listing View'), ('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down'), ('analyze', 'Analyzed with Zelda'), ('memo_view', 'Viewed Intelligence Memo'), ('truth_delta_view', 'Viewed Truth Delta'), ('intro_request', 'Requested Introduction'), ('message_sent', 'Sent Direct Message'), ('closed', 'Deal Closed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_events', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_events', to='matchmaking.sellerapplication')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', '-created_at'], name='matchmaking_seller__8af86a_idx'), models.Index(fields=['buyer', '-created_at'], name='matchmaking_buyer_i_63d39f_idx'), models.Index(fields=['event_type'], name='matchmaking_event_t_f0d0ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='AcquisitionConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('initiated_by', models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller')], default='BUYER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('needs_attention', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition_connections', to='matchmaking.buyerapplication')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition_connections', to='matchmaking.sellerapplication')),
            ],
            options={
                'verbose_name': 'Acquisition Connection',
                'verbose_name_plural': 'Acquisition Connections',
                'unique_together': {('buyer', 'seller')},
            },
        ),
    ]
