# Generated by Django 6.0.4 on 2026-07-04 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0036_buyerapplication_sellerapplication_dealfeedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPredictionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_score', models.FloatField()),
                ('runner_up_sellers', models.JSONField(blank=True, default=list, help_text='Top 5 [{seller_id, score}] at snapshot time')),
                ('snapshot_telemetry', models.JSONField(blank=True, default=dict, help_text='AcquisitionInterestEvent counts + vector presence at snapshot time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A — Predicted Correctly'), ('B', 'B — Industry/Size/Structure Sound, Buyer Deviated'), ('C', 'C — Partial Signal Match'), ('D', 'D — Weak Signal Match'), ('F', 'F — Missed Entirely')], max_length=1, null=True)),
                ('grade_score', models.FloatField(blank=True, help_text='0-100 raw score before A-F bucketing', null=True)),
                ('grade_explanation', models.TextField(blank=True)),
                ('actual_closed_seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_prediction_snapshots', to='matchmaking.sellerapplication')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_snapshots', to='matchmaking.buyerapplication')),
                ('predicted_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_by_snapshots', to='matchmaking.sellerapplication')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['buyer', '-created_at'], name='matchmaking_buyer_i_2c6fce_idx'), models.Index(fields=['is_resolved'], name='matchmaking_is_reso_4565f1_idx')],
            },
        ),
    ]
