# Generated by Django 6.0.4 on 2026-07-04 17:41

import django.core.validators
import matchmaking.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0037_buyerpredictionsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='pitch_deck',
            field=models.FileField(blank=True, null=True, upload_to='decks/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'pptx']), matchmaking.validators.MaxFileSizeValidator(max_mb=25)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='pitch_video',
            field=models.FileField(blank=True, help_text='Upload a short 1-3 minute video pitch (MP4, MOV, WEBM). Max 200MB.', null=True, upload_to='pitch_videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm']), matchmaking.validators.MaxFileSizeValidator(max_mb=200)]),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='cim_document',
            field=models.FileField(blank=True, help_text='Confidential Information Memorandum — the standard M&A teaser/info packet. Max 25MB.', null=True, upload_to='cim_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'pptx']), matchmaking.validators.MaxFileSizeValidator(max_mb=25)]),
        ),
    ]
