# Generated by Django 6.0.4 on 2026-07-04 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0038_alter_application_pitch_deck_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_private', 'review_status'], name='matchmaking_is_priv_8066d9_idx'),
        ),
        migrations.AddIndex(
            model_name='buyerapplication',
            index=models.Index(fields=['is_private', 'review_status'], name='matchmaking_is_priv_79b475_idx'),
        ),
        migrations.AddIndex(
            model_name='investorapplication',
            index=models.Index(fields=['is_private', 'review_status'], name='matchmaking_is_priv_27c1fd_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerapplication',
            index=models.Index(fields=['is_private', 'review_status'], name='matchmaking_is_priv_fedf3b_idx'),
        ),
    ]
