# Generated by Django 6.0.4 on 2026-07-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0039_application_matchmaking_is_priv_8066d9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Founder Premium: Featured Placement on the bulletin board.'),
        ),
    ]
