# Generated by Django 6.0.4 on 2026-07-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0040_application_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Seller Premium: Featured Listing in the business marketplace.'),
        ),
    ]
