# Generated by Django 6.0.4 on 2026-07-05 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0041_sellerapplication_is_premium'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('event_type', models.CharField(choices=[('landing_view', 'Landing Page View'), ('signup_started', 'Signup Page Viewed'), ('signup_completed', 'Signup Completed')], max_length=20)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='matchmaking_event_t_4a0cfa_idx'), models.Index(fields=['session_key'], name='matchmaking_session_e7a8bf_idx')],
            },
        ),
    ]
