# Generated by Django 6.0.4 on 2026-07-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0042_pageevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_staff_featured',
            field=models.BooleanField(default=False, help_text='Staff-curated Featured Placement — independent of paid premium status.'),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='is_staff_featured',
            field=models.BooleanField(default=False, help_text='Staff-curated Featured Listing — independent of paid premium status.'),
        ),
        migrations.AlterField(
            model_name='acquisitionconnection',
            name='initiated_by',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('STAFF', 'Staff (Manual Intro)')], default='BUYER', max_length=20),
        ),
        migrations.AlterField(
            model_name='connection',
            name='initiated_by',
            field=models.CharField(choices=[('INVESTOR', 'Investor'), ('FOUNDER', 'Founder'), ('STAFF', 'Staff (Manual Intro)')], default='INVESTOR', max_length=20),
        ),
    ]
