# Generated by Django 6.0.4 on 2026-07-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0043_application_is_staff_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_hidden_by_staff',
            field=models.BooleanField(default=False, help_text='Hides this pitch deck/video from everyone except the owner and staff.'),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='is_hidden_by_staff',
            field=models.BooleanField(default=False, help_text="Hides this listing's CIM document from everyone except the owner and staff."),
        ),
    ]
