# Generated by Django 6.0.4 on 2026-07-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0044_application_is_hidden_by_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorapplication',
            name='ticket_size_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Maximum Check Size'),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='ticket_size_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Minimum Check Size'),
        ),
    ]
