# Generated by Django 6.0.4 on 2026-07-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0045_investorapplication_ticket_size_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='capital_plan_vector',
            field=models.JSONField(blank=True, help_text="Embedding of 'reason_for_capital'.", null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='market_context_vector',
            field=models.JSONField(blank=True, help_text='Embedding of sector/stage/geography combined.', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='problem_solution_vector',
            field=models.JSONField(blank=True, help_text="Embedding of 'description' (Executive Summary).", null=True),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='thesis_vector',
            field=models.JSONField(blank=True, help_text='Embedding of investment_thesis_summary (or investment_focus if blank).', null=True),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='weight_capital_plan',
            field=models.FloatField(default=0.333, help_text='How much to weigh capital-plan/use-of-funds fit (0-1).'),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='weight_market_context',
            field=models.FloatField(default=0.333, help_text='How much to weigh sector/stage/geography fit (0-1).'),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='weight_problem_solution',
            field=models.FloatField(default=0.334, help_text='How much to weigh problem/solution fit (0-1).'),
        ),
    ]
