# Generated by Django 6.0.4 on 2026-07-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0046_application_capital_plan_vector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTrainingExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_type', models.CharField(choices=[('INVESTOR', 'Investor'), ('BUYER', 'Buyer')], max_length=20)),
                ('anchor_id', models.PositiveIntegerField()),
                ('candidate_type', models.CharField(choices=[('FOUNDER', 'Founder'), ('SELLER', 'Seller')], max_length=20)),
                ('candidate_id', models.PositiveIntegerField()),
                ('label', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative')], max_length=20)),
                ('source', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down'), ('funded', 'Deal Funded'), ('closed', 'Deal Closed'), ('ops_override', 'Staff Override'), ('ops_manual_intro', 'Staff Manual Intro')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['anchor_type', 'anchor_id'], name='matchmaking_anchor__b2c109_idx'), models.Index(fields=['label', 'source'], name='matchmaking_label_c9f96e_idx')],
            },
        ),
    ]
