# Generated by Django 6.0.4 on 2026-07-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0047_matchtrainingexample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchtrainingexample',
            name='source',
            field=models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down'), ('funded', 'Deal Funded'), ('closed', 'Deal Closed'), ('declined', 'Declined'), ('ops_override', 'Staff Override'), ('ops_manual_intro', 'Staff Manual Intro')], max_length=20),
        ),
    ]
