# Postgres-only monthly RANGE partitioning for PageEvent and
# MatchTrainingExample — the two tables that grow unboundedly with normal
# platform usage. No Django model/state changes here at all: Postgres
# partitioned tables are queried through the parent table name exactly like
# an ordinary table, so the ORM doesn't need to know anything changed.
#
# A DEFAULT partition catches any row outside an explicitly-created monthly
# range, so this is safe even if the ensure_next_month_partition beat task
# (matchmaking/tasks.py) ever fails to run — inserts still succeed, they
# just land in the (unindexed-by-month) default partition instead of a
# dedicated one, a pure performance degradation, never a correctness one.
#
# No-op on SQLite (the local dev default) — both tables stay exactly as
# they are today.

from django.db import migrations


def _partition_table(cursor, table, columns_sql, copy_columns, index_statements):
    cursor.execute(f"ALTER TABLE {table} RENAME TO {table}_unpartitioned;")
    cursor.execute(f"""
        CREATE TABLE {table} (
            {columns_sql}
        ) PARTITION BY RANGE (created_at);
    """)
    cursor.execute(f"CREATE TABLE {table}_default PARTITION OF {table} DEFAULT;")
    cursor.execute(f"""
        INSERT INTO {table} ({copy_columns})
        SELECT {copy_columns} FROM {table}_unpartitioned;
    """)
    cursor.execute(f"""
        SELECT setval(pg_get_serial_sequence('{table}', 'id'),
                      COALESCE((SELECT MAX(id) FROM {table}), 1));
    """)
    for stmt in index_statements:
        cursor.execute(stmt)
    cursor.execute(f"DROP TABLE {table}_unpartitioned;")


def partition_tables(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        _partition_table(
            cursor,
            table='matchmaking_pageevent',
            columns_sql="""
                id bigint GENERATED BY DEFAULT AS IDENTITY,
                session_key varchar(40) NOT NULL,
                user_id integer NULL REFERENCES auth_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
                event_type varchar(20) NOT NULL,
                role varchar(20) NOT NULL,
                created_at timestamptz NOT NULL
            """,
            copy_columns="id, session_key, user_id, event_type, role, created_at",
            index_statements=[
                "CREATE INDEX matchmaking_pe_event_created_idx ON matchmaking_pageevent (event_type, created_at DESC);",
                "CREATE INDEX matchmaking_pe_session_idx ON matchmaking_pageevent (session_key);",
                "CREATE INDEX matchmaking_pe_user_idx ON matchmaking_pageevent (user_id);",
            ],
        )
        _partition_table(
            cursor,
            table='matchmaking_matchtrainingexample',
            columns_sql="""
                id bigint GENERATED BY DEFAULT AS IDENTITY,
                anchor_type varchar(20) NOT NULL,
                anchor_id integer NOT NULL,
                candidate_type varchar(20) NOT NULL,
                candidate_id integer NOT NULL,
                label varchar(20) NOT NULL,
                source varchar(20) NOT NULL,
                created_at timestamptz NOT NULL
            """,
            copy_columns="id, anchor_type, anchor_id, candidate_type, candidate_id, label, source, created_at",
            index_statements=[
                "CREATE INDEX matchmaking_mte_anchor_idx ON matchmaking_matchtrainingexample (anchor_type, anchor_id);",
                "CREATE INDEX matchmaking_mte_label_source_idx ON matchmaking_matchtrainingexample (label, source);",
            ],
        )


def unpartition_tables(apps, schema_editor):
    # Not implemented — reversing partitioned-table DDL safely requires the
    # same rename/recreate/copy dance in reverse, and this migration is not
    # expected to be rolled back in practice. Left as a hard stop rather
    # than a silent partial reverse.
    if schema_editor.connection.vendor != 'postgresql':
        return
    raise NotImplementedError("Reversing table partitioning is not supported.")


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0049_pgvector_shadow_columns'),
    ]

    operations = [
        migrations.RunPython(partition_tables, unpartition_tables),
    ]
