# Generated by Django 6.0.4 on 2026-07-13 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0052_profile_view_video_message_thread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pageevent',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pageevent',
            name='event_type',
            field=models.CharField(choices=[('landing_view', 'Landing Page View'), ('signup_started', 'Signup Page Viewed'), ('signup_completed', 'Signup Completed'), ('dashboard_view', 'Dashboard/Match List Viewed')], max_length=20),
        ),
        migrations.CreateModel(
            name='SearchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('source', models.CharField(choices=[('filter_search', 'Filter Search'), ('zelda_ai_search', 'Zelda AI Search')], max_length=20)),
                ('query_summary', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='matchmaking_user_id_a490ca_idx'), models.Index(fields=['-created_at'], name='matchmaking_created_54c0d0_idx')],
            },
        ),
    ]
