# Generated by Django 6.0.4 on 2026-07-13 18:45

import django.core.validators
import django.db.models.deletion
import matchmaking.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0054_businessemailverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRoomDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='data_room/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'xlsx', 'csv', 'pptx']), matchmaking.validators.MaxFileSizeValidator(max_mb=25)])),
                ('category', models.CharField(choices=[('CAP_TABLE', 'Cap Table'), ('FINANCIALS', 'Financials'), ('LEGAL_IP', 'Legal / IP'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_room_documents', to='matchmaking.application')),
            ],
            options={
                'ordering': ['category', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRoomDocumentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_log', to='matchmaking.dataroomdocument')),
                ('viewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_room_views_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataRoomAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_room_requests', to='matchmaking.investorapplication')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='matchmaking.dataroomdocument')),
            ],
            options={
                'unique_together': {('document', 'investor')},
            },
        ),
    ]
