# Generated by Django 6.0.4 on 2026-07-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0055_dataroomdocument_dataroomdocumentview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchevent',
            name='source',
            field=models.CharField(choices=[('filter_search', 'Filter Search'), ('zelda_ai_search', 'Zelda AI Search'), ('zelda_ask', 'Ask Zelda (NL Query)')], max_length=20),
        ),
    ]
