# Generated by Django 6.0.4 on 2026-07-14 22:15

import django.core.validators
import django.db.models.deletion
import matchmaking.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0056_alter_searchevent_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pitch_video_comments_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='pitch_video_likes',
            field=models.ManyToManyField(blank=True, related_name='liked_founder_pitch_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='pitch_video_notify_on_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='pitch_video_saves',
            field=models.ManyToManyField(blank=True, related_name='saved_founder_pitch_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='pitch_video_shares_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='pitch_video_show_like_count',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pitch_video',
            field=models.FileField(blank=True, help_text="Upload a short 1-3 minute video walking through why you're selling, growth opportunities, and the ideal buyer (MP4, MOV, WEBM). Max 200MB.", null=True, upload_to='pitch_videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm']), matchmaking.validators.MaxFileSizeValidator(max_mb=200)]),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pitch_video_comments_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pitch_video_likes',
            field=models.ManyToManyField(blank=True, related_name='liked_seller_pitch_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pitch_video_notify_on_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pitch_video_saves',
            field=models.ManyToManyField(blank=True, related_name='saved_seller_pitch_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pitch_video_shares_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pitch_video_show_like_count',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PitchVideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_video_comments_made', to=settings.AUTH_USER_MODEL)),
                ('founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitch_video_comments', to='matchmaking.application')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitch_video_comments', to='matchmaking.sellerapplication')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['founder', '-created_at'], name='matchmaking_founder_37b6a7_idx'), models.Index(fields=['seller', '-created_at'], name='matchmaking_seller__008c48_idx')],
            },
        ),
    ]
