# Generated by Django 6.0.4 on 2026-07-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0057_application_pitch_video_comments_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisitioninterestevent',
            name='event_type',
            field=models.CharField(choices=[('video_play', 'Pitch Video Played'), ('view', 'Listing View'), ('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down'), ('analyze', 'Analyzed with Zelda'), ('memo_view', 'Viewed Intelligence Memo'), ('truth_delta_view', 'Viewed Truth Delta'), ('intro_request', 'Requested Introduction'), ('message_sent', 'Sent Direct Message'), ('closed', 'Deal Closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='investorinterestevent',
            name='event_type',
            field=models.CharField(choices=[('video_play', 'Pitch Video Played'), ('view', 'Profile View'), ('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down'), ('analyze', 'Analyzed with Zelda'), ('memo_view', 'Viewed Intelligence Memo'), ('truth_delta_view', 'Viewed Truth Delta'), ('intro_request', 'Requested Introduction'), ('message_sent', 'Sent Direct Message'), ('funded', 'Deal Funded')], max_length=20),
        ),
    ]
