# Generated by Django 6.0.4 on 2026-07-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0058_alter_acquisitioninterestevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pitch_video_visibility',
            field=models.CharField(choices=[('SITE_WIDE', 'Everyone (Pitch Videos section)'), ('ROLE_ONLY', 'Investors only'), ('PROFILE_ONLY', 'Off — profile page only')], default='SITE_WIDE', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='pitch_video_visibility',
            field=models.CharField(choices=[('SITE_WIDE', 'Everyone (Pitch Videos section)'), ('ROLE_ONLY', 'Buyers only'), ('PROFILE_ONLY', 'Off — profile page only')], default='SITE_WIDE', max_length=20),
        ),
    ]
