# Generated by Django 6.0.4 on 2026-07-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0059_application_pitch_video_visibility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimatch',
            options={'ordering': ['-score'], 'verbose_name': 'AI Match', 'verbose_name_plural': 'AI Matches'},
        ),
        migrations.AddField(
            model_name='aimatch',
            name='change_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aimatch',
            name='last_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='aimatch',
            constraint=models.UniqueConstraint(fields=('investor', 'application'), name='unique_investor_application_match'),
        ),
    ]
