# Generated by Django 6.0.4 on 2026-07-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0060_alter_aimatch_options_aimatch_change_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimatch',
            name='score_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
