# Generated by Django 6.0.4 on 2026-07-17 07:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0061_aimatch_score_generated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestEngagementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sent', 'Digest Sent'), ('opened', 'Digest Opened'), ('clicked', 'Hero Match Clicked')], max_length=10)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_engagement_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['token', 'event_type'], name='matchmaking_token_03736f_idx'), models.Index(fields=['event_type', '-created_at'], name='matchmaking_event_t_73f3ac_idx')],
            },
        ),
    ]
