# Generated by Django 6.0.4 on 2026-07-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0062_digestengagementevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_highlight_at',
            field=models.DateTimeField(blank=True, help_text='Founder Premium: last time the monthly 24-hour highlight boost was activated.', null=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='last_highlight_at',
            field=models.DateTimeField(blank=True, help_text='Seller Premium: last time the monthly 24-hour highlight boost was activated.', null=True),
        ),
    ]
