# Generated by Django 6.0.4 on 2026-08-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0064_firm_firmmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='runway_months',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True),
        ),
    ]
