# Generated by Django 6.0.4 on 2026-08-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0065_alter_application_runway_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pitch_deck_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
