# Generated by Django 6.0.4 on 2026-08-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0066_application_pitch_deck_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text="Set when the founder archives this profile — hidden from discovery like is_private, but distinct so the owner can tell 'paused' apart from 'incognito' and reactivate it.", null=True),
        ),
    ]
