# Generated by Django 6.0.4 on 2026-08-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0067_application_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerapplication',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text="Set when the buyer archives this mandate — hidden from discovery like is_private, but distinct so the owner can tell 'paused' apart from 'incognito' and reactivate it.", null=True),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text="Set when the investor archives this mandate — hidden from discovery like is_private, but distinct so the owner can tell 'paused' apart from 'incognito' and reactivate it.", null=True),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text="Set when the seller archives this listing — hidden from discovery like is_private, but distinct so the owner can tell 'paused' apart from 'incognito' and reactivate it.", null=True),
        ),
    ]
