# Generated by Django 6.0.4 on 2026-08-31 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0068_buyerapplication_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataroomdocument',
            name='category',
            field=models.CharField(choices=[('CAP_TABLE', 'Cap Table'), ('FINANCIALS', 'Financials'), ('CUSTOMER_METRICS', 'Customer Metrics'), ('REVENUE_BREAKDOWN', 'Revenue Breakdown'), ('CONTRACTS', 'Contracts'), ('LEGAL_IP', 'Legal / IP'), ('PRODUCT_ROADMAP', 'Product Roadmap'), ('TEAM_INFO', 'Team Information'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.CreateModel(
            name='DataRoomInformationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CAP_TABLE', 'Cap Table'), ('FINANCIALS', 'Financials'), ('CUSTOMER_METRICS', 'Customer Metrics'), ('REVENUE_BREAKDOWN', 'Revenue Breakdown'), ('CONTRACTS', 'Contracts'), ('LEGAL_IP', 'Legal / IP'), ('PRODUCT_ROADMAP', 'Product Roadmap'), ('TEAM_INFO', 'Team Information'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('DECLINED', 'Declined')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_room_information_requests', to='matchmaking.application')),
                ('fulfilled_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_information_requests', to='matchmaking.dataroomdocument')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_room_information_requests', to='matchmaking.investorapplication')),
            ],
            options={
                'unique_together': {('founder', 'investor', 'category')},
            },
        ),
    ]
