# Generated by Django 6.0.4 on 2026-09-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0069_alter_dataroomdocument_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataroomaccessrequest',
            name='nda_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataroomdocument',
            name='visibility',
            field=models.CharField(choices=[('MATCH_ONLY', 'Any Connected Investor — no approval needed'), ('INVESTOR_APPROVED', 'Requires Founder Approval'), ('NDA_REQUIRED', 'Requires Approval + NDA Acknowledgment')], default='INVESTOR_APPROVED', max_length=20),
        ),
    ]
