# Generated by Django 6.0.4 on 2026-09-01 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0070_dataroomaccessrequest_nda_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='deal_room',
        ),
        migrations.DeleteModel(
            name='DealRoom',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
