# Generated by Django 6.0.4 on 2026-09-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0071_remove_document_deal_room_delete_dealroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='funded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
