# Generated by Django 6.0.4 on 2026-09-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0072_connection_accepted_at_connection_funded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisitionconnection',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acquisitionconnection',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
