# Generated by Django 6.0.4 on 2026-09-01 22:17

import django.core.validators
import django.db.models.deletion
import matchmaking.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0073_acquisitionconnection_accepted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ELEVATOR_PITCH', 'Elevator Pitch (=<30s)')], default='ELEVATOR_PITCH', max_length=32)),
                ('video', models.FileField(help_text='=<30 seconds. MP4, MOV, or WEBM. Max 30MB.', upload_to='elevator_pitches/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm']), matchmaking.validators.MaxFileSizeValidator(max_mb=30)])),
                ('caption', models.CharField(blank=True, help_text="One line shown under your video in Explore - the one-sentence version of what you're building.", max_length=140)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Reported by the browser at upload time.', null=True)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('QUARANTINED', 'Quarantined - under review'), ('REMOVED', 'Removed by staff')], default='PUBLISHED', max_length=16)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('completed_view_count', models.PositiveIntegerField(default=0, help_text='Views that reached >=90% of the clip.')),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('first_reported_at', models.DateTimeField(blank=True, null=True)),
                ('quarantined_at', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_review_decision', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_videos', to='matchmaking.application')),
                ('interested_users', models.ManyToManyField(blank=True, related_name='interested_profile_videos', to=settings.AUTH_USER_MODEL)),
                ('last_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_videos_reviewed', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_videos', to='matchmaking.sellerapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileVideoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SCAM', 'Scam / fraudulent claim'), ('IMPERSONATION', 'Impersonation'), ('MISLEADING', 'Misleading information'), ('INAPPROPRIATE', 'Inappropriate content'), ('IP', 'Copyright / IP concern'), ('SPAM', 'Spam'), ('OTHER', 'Other')], max_length=16)),
                ('detail', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending review'), ('RESTORED', 'Restored - report not upheld'), ('UPHELD', 'Upheld - video removed')], default='PENDING', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_video_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_video_reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='matchmaking.profilevideo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='profilevideo',
            index=models.Index(fields=['kind', 'status', '-created_at'], name='matchmaking_kind_b8261a_idx'),
        ),
        migrations.AddIndex(
            model_name='profilevideo',
            index=models.Index(fields=['status', 'first_reported_at'], name='matchmaking_status_aa9c09_idx'),
        ),
        migrations.AddConstraint(
            model_name='profilevideo',
            constraint=models.UniqueConstraint(condition=models.Q(('founder__isnull', False)), fields=('founder', 'kind'), name='uniq_founder_video_kind'),
        ),
        migrations.AddConstraint(
            model_name='profilevideo',
            constraint=models.UniqueConstraint(condition=models.Q(('seller__isnull', False)), fields=('seller', 'kind'), name='uniq_seller_video_kind'),
        ),
        migrations.AddConstraint(
            model_name='profilevideoreport',
            constraint=models.UniqueConstraint(condition=models.Q(('reporter__isnull', False)), fields=('video', 'reporter'), name='uniq_report_per_user_per_video'),
        ),
    ]
