# Generated by Django 6.0.4 on 2026-09-07 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0074_profilevideo_profilevideoreport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimatch',
            name='confidence_score',
        ),
    ]
