# Generated by Django 6.0.4 on 2026-09-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0075_remove_aimatch_confidence_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerpredictionsnapshot',
            name='match_contract_version',
            field=models.CharField(blank=True, help_text='Which Match Score contract produced predicted_score/band. BLANK MEANS PRE-CONTRACT: those rows were written under the old blended scale and must not be read as v1 predictions or graded against v1 semantics.', max_length=8),
        ),
        migrations.AddField(
            model_name='buyerpredictionsnapshot',
            name='predicted_band',
            field=models.CharField(blank=True, help_text='Match band at snapshot time. Blank on rows written before the contract existed.', max_length=16),
        ),
        migrations.AddField(
            model_name='buyerpredictionsnapshot',
            name='predicted_basis',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many components contributed. Blank on pre-contract rows.', null=True),
        ),
        migrations.AddField(
            model_name='investorpredictionsnapshot',
            name='match_contract_version',
            field=models.CharField(blank=True, help_text='Which Match Score contract produced predicted_score/band. BLANK MEANS PRE-CONTRACT: those rows were written under the old blended scale and must not be read as v1 predictions or graded against v1 semantics.', max_length=8),
        ),
        migrations.AddField(
            model_name='investorpredictionsnapshot',
            name='predicted_band',
            field=models.CharField(blank=True, help_text='Match band at snapshot time. Blank on rows written before the contract existed.', max_length=16),
        ),
        migrations.AddField(
            model_name='investorpredictionsnapshot',
            name='predicted_basis',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many components contributed. Blank on pre-contract rows.', null=True),
        ),
    ]
