# Generated by Django 6.0.4 on 2026-09-20 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0076_snapshot_match_contract_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDealRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, help_text='Who hosts it — DocSend, Box, Dropbox, Google Drive. Free text: naming providers in code would read as an endorsement of them.', max_length=100)),
                ('external_url', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('access_instructions', models.TextField(blank=True, help_text="How a granted investor gets in — e.g. 'request access with the email on your Interlink profile'. Never put a password here.")),
                ('is_active', models.BooleanField(default=True, help_text='Unset to take the room down for everyone but the owner, without deleting the grant history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text="When the OWNER last confirmed the link still works. Interlink never fetches the URL to check — that would be a request to the provider on the founder's behalf, and it would show up in their access logs as us.", null=True)),
                ('founder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_deal_room', to='matchmaking.application')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalDealRoomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Room created'), ('URL_CHANGED', 'Link changed'), ('DETAILS_CHANGED', 'Details changed'), ('GRANTED', 'Access granted'), ('REVOKED', 'Access revoked'), ('DEACTIVATED', 'Room deactivated'), ('REACTIVATED', 'Room reactivated'), ('VIEWED', 'Link viewed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='Who did it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_deal_room_actions', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matchmaking.externaldealroom')),
                ('subject', models.ForeignKey(blank=True, help_text='Who it was done to, for grant and revoke.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_deal_room_events_about', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalDealRoomGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_deal_room_grants', to='matchmaking.investorapplication')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='matchmaking.externaldealroom')),
            ],
            options={
                'unique_together': {('room', 'investor')},
            },
        ),
    ]
