# Generated by Django 6.0.4 on 2026-09-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0077_externaldealroom_externaldealroomevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='field_visibility',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='field_visibility_defaults_applied_at',
            field=models.DateTimeField(blank=True, help_text="When the one-time backfill wrote this profile's starting visibility. Distinguishes 'migrated, then the founder cleared it' from 'never migrated', which an empty field_visibility alone cannot.", null=True),
        ),
    ]
