# Generated by Django 6.0.4 on 2026-09-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0079_backfill_field_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='field_visibility',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='field_visibility_defaults_applied_at',
            field=models.DateTimeField(blank=True, help_text="When the one-time backfill wrote this listing's starting visibility.", null=True),
        ),
    ]
