# Generated by Django 6.0.4 on 2026-09-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0081_backfill_seller_field_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerapplication',
            name='allow_direct_messages',
            field=models.BooleanField(default=False, help_text='If True, verified users can bypass the matchmaking radar to initiate a Deal Room chat.'),
        ),
        migrations.AddField(
            model_name='sellerapplication',
            name='allow_direct_messages',
            field=models.BooleanField(default=False, help_text='If True, verified users can bypass the matchmaking radar to initiate a Deal Room chat.'),
        ),
    ]
