# Generated by Django 6.0.4 on 2026-10-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0082_seller_buyer_allow_direct_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='revenue_as_of',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='revenue_period',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual (a full fiscal year)'), ('ttm', 'Trailing 12 months'), ('arr', 'Annual recurring run-rate (ARR)')], default='', max_length=10),
        ),
    ]
