# Generated by Django 6.0.4 on 2026-05-15 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('investment_focus', models.CharField(max_length=255)),
                ('investment_stage', models.CharField(max_length=50)),
                ('investment_amount', models.DecimalField(decimal_places=2, help_text='Average check size', max_digits=15)),
                ('min_check', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_check', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('location_preference', models.CharField(default='Global', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('focus_vector', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
