# Generated by Django 6.0.4 on 2026-05-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Current Annual Recurring Revenue (ARR)', max_digits=15, null=True)),
                ('company_size', models.PositiveIntegerField(blank=True, help_text='Number of full-time employees', null=True)),
                ('years_in_business', models.PositiveIntegerField(default=0, help_text='Years since incorporation')),
            ],
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='years_in_business',
            field=models.PositiveIntegerField(default=0, help_text='Years firm has been active'),
        ),
    ]
