# Generated by Django 6.0.4 on 2026-05-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_application_investorapplication_years_in_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='revenue',
            new_name='current_revenue',
        ),
    ]
