# Generated by Django 6.0.4 on 2026-05-23 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_revenue_application_current_revenue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='FounderApplication',
        ),
    ]
