# Generated by Django 6.0.4 on 2026-05-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_founderapplication_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorapplication',
            name='historical_vector_embedding',
            field=models.JSONField(blank=True, help_text='Mathematical representation of past deals', null=True),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='portfolio_raw_text',
            field=models.TextField(blank=True, help_text='Scraped from their uploaded PDF/Deck', null=True),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='stated_thesis',
            field=models.TextField(blank=True, help_text='What they typed in the form', null=True),
        ),
    ]
