# Generated by Django 6.0.3 on 2026-05-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_companyprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='FounderProfile',
        ),
    ]
