# Generated by Django 6.0.4 on 2026-05-27 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_investorapplication_historical_vector_embedding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='founderapplication',
            name='allowed_viewers',
            field=models.ManyToManyField(blank=True, help_text='Investors authorized to audit this company via invite workflow matches.', related_name='permitted_founder_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='founderapplication',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Incognito Mode: Hides your pitch tracking records from public bulletin boards, global metrics grids, and Zelda AI.'),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='allowed_viewers',
            field=models.ManyToManyField(blank=True, help_text='Users granted direct access via accepted invitation paths.', related_name='permitted_investor_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Incognito Mode: Hides your mandate from dashboards, smart filters, and global AI memo index tools.'),
        ),
        migrations.AlterField(
            model_name='founderapplication',
            name='current_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current Annual Recurring Recurring Revenue (ARR)', max_digits=15, null=True),
        ),
    ]
