# Generated by Django 6.0.3 on 2026-05-02 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_founderapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('company_name', models.CharField(max_length=255)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('business_description', models.TextField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(blank=True, max_length=50)),
                ('raising_amount', models.CharField(blank=True, max_length=50)),
                ('years_in_business', models.IntegerField(blank=True, null=True)),
                ('company_size', models.CharField(blank=True, max_length=50)),
                ('amount_raised', models.CharField(blank=True, max_length=50)),
                ('reason_for_capital', models.TextField(blank=True)),
                ('extra_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FounderApplication',
        ),
    ]
