# Generated by Django 6.0.4 on 2026-06-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_founderapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='founderapplication',
            name='monthly_burn_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average monthly cash burn in USD', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='founderapplication',
            name='raising_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='founderapplication',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of full-time employees', null=True),
        ),
    ]
