# Generated by Django 6.0.4 on 2026-06-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_founderapplication_monthly_burn_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founderapplication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founderapplication',
            name='stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='founderapplication',
            name='funding_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
