# Generated by Django 6.0.3 on 2026-05-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_user_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.RemoveField(
            model_name='application',
            name='updated_at',
        ),
    ]
