# Generated by Django 6.0.4 on 2026-06-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_founderapplication_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founderapplication',
            name='allow_direct_messages',
            field=models.BooleanField(default=False, help_text='If True, verified users can bypass the matchmaking radar to initiate a Deal Room chat.'),
        ),
        migrations.AddField(
            model_name='investorapplication',
            name='allow_direct_messages',
            field=models.BooleanField(default=False, help_text='If True, verified users can bypass the matchmaking radar to initiate a Deal Room chat.'),
        ),
    ]
