# Generated by Django 6.0.3 on 2026-05-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_application_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='current_revenue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
