# Generated by Django 6.0.4 on 2026-06-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_founderapplication_allow_direct_messages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founderapplication',
            name='allow_direct_messages',
        ),
        migrations.RemoveField(
            model_name='investorapplication',
            name='allow_direct_messages',
        ),
    ]
