# Generated by Django 6.0.4 on 2026-09-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_founderapplication_allow_direct_messages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32)),
                ('key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'key', 'created_at'], name='accounts_ra_scope_f69d7b_idx'), models.Index(fields=['created_at'], name='accounts_ra_created_649a30_idx')],
            },
        ),
    ]
