# Generated by Django 6.0.3 on 2026-05-05 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_application_prior_amount_raised'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='amount_raised',
        ),
    ]
