# Generated by Django 6.0.4 on 2026-05-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_investor_dealflowlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealflowlog',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AddField(
            model_name='application',
            name='investors',
            field=models.ManyToManyField(blank=True, related_name='applications', through='accounts.DealFlowLog', to='accounts.investor'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='dealflowlog',
            unique_together={('investor', 'application')},
        ),
    ]
