# Generated by Django 6.0.4 on 2026-05-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_delete_post_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='company_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
