# Generated by Django 6.0.4 on 2026-05-25 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerGridAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('solar_farm', 'Solar Generation Facility'), ('wind_turbine', 'Wind Array Facility'), ('natural_gas', 'Natural Gas Peaker Plant'), ('battery_storage', 'BESS Battery Storage Bank')], default='solar_farm', max_length=30)),
                ('grid_region', models.CharField(help_text='e.g., CAISO, ERCOT, PJM', max_length=50)),
                ('nameplate_capacity_mw', models.FloatField(help_text='Maximum design output capacity in Megawatts.')),
                ('status', models.CharField(choices=[('operational', 'Operational / Nominal Grid Tie'), ('maintenance', 'Offline for Maintenance'), ('curtailed', 'Curtailed by Grid Operator')], default='operational', max_length=20)),
                ('last_reported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Power Grid Asset',
                'verbose_name_plural': 'Power Grid Assets',
            },
        ),
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_output_mw', models.FloatField(help_text='Instantaneous output in Megawatts.')),
                ('grid_frequency_hz', models.FloatField(default=60.0)),
                ('carbon_offset_intensity', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.UUIDField(blank=True, null=True, unique=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_logs', to='energy_api.powergridasset')),
            ],
            options={
                'verbose_name': 'Generation Log',
                'verbose_name_plural': 'Generation Logs',
                'indexes': [models.Index(fields=['asset', 'recorded_at'], name='energy_api__asset_i_e543ec_idx'), models.Index(fields=['idempotency_key'], name='energy_api__idempot_f4b73c_idx')],
            },
        ),
    ]
