# Generated by Django 6.0.4 on 2026-05-20 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional name for groups/deal rooms.', max_length=255, null=True)),
                ('thread_type', models.CharField(choices=[('direct', 'Direct Message (1-on-1)'), ('group', 'Group Venture Channel'), ('deal_room', 'Secure Deal Room Negotiation')], default='direct', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Thread',
                'verbose_name_plural': 'Chat Threads',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('zelda_moderation_metadata', models.JSONField(blank=True, default=dict, help_text='Stores parsed sentiment metrics, safety scores, or urgency flags.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging_api.chatthread')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
