# Generated by Django 6.0.4 on 2026-07-06 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInsightReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('period_label', models.CharField(help_text='e.g. "Q3 2026"', max_length=50)),
                ('period_slug', models.SlugField(max_length=60, unique=True)),
                ('body_sections', models.JSONField(default=list, help_text='List of {"heading": str, "text": str} sections.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(max_length=254)),
                ('role_hint', models.CharField(choices=[('INVESTOR', 'Investor'), ('FOUNDER', 'Founder')], max_length=20)),
                ('code', models.CharField(editable=False, max_length=32, unique=True)),
                ('source', models.CharField(choices=[('fundraising_lead', 'Fundraising CRM Lead'), ('deal_pulse_portfolio', 'Deal Pulse Portfolio Company')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('reward_granted', models.BooleanField(default=False)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
