# Generated by Django 6.0.4 on 2026-07-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text="Dotted Celery task path, e.g. 'matchmaking.tasks.send_weekly_digests'.", max_length=255)),
                ('args_json', models.JSONField(blank=True, default=list, help_text='Positional args the task was originally called with, for requeueing.')),
                ('exception_message', models.TextField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
    ]
