# Generated by Django 6.0.4 on 2026-09-14 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_failedtasklog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='impersonationlog',
            name='impersonator_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='impersonationlog',
            name='target_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userreport',
            name='reported_username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='impersonationlog',
            name='impersonator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonation_sessions_started', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='impersonationlog',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonation_sessions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_filed', to=settings.AUTH_USER_MODEL),
        ),
    ]
