# Generated by Django 6.0.4 on 2026-07-02 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_invitation_requests', models.BooleanField(default=True)),
                ('accept_follow_requests', models.BooleanField(default=True)),
                ('blog_likes_enabled', models.BooleanField(default=True)),
                ('blog_comments_enabled', models.BooleanField(default=True)),
                ('show_job_postings', models.BooleanField(default=True)),
                ('show_articles', models.BooleanField(default=True)),
                ('show_business_connections', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
