# Generated by Django 6.0.4 on 2026-07-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='show_contact_info',
            field=models.BooleanField(default=True),
        ),
    ]
