# Generated by Django 6.0.4 on 2026-07-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0002_usersettings_show_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='show_milestones',
            field=models.BooleanField(default=True),
        ),
    ]
