# Generated by Django 6.0.4 on 2026-07-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0003_usersettings_show_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='show_profile_view_count',
            field=models.BooleanField(default=True),
        ),
    ]
