# Generated by Django 6.0.4 on 2026-08-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0004_show_profile_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Populated from Google/Facebook/LinkedIn on first social signup; replaceable anytime from Settings.', null=True, upload_to='profile_pictures/%Y/%m/'),
        ),
    ]
