# Generated by Django 6.0.4 on 2026-05-20 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('code_template', 'Code Architecture & Boilerplates'), ('dataset', 'Structured Data & Vector Vectors'), ('ai_prompt', 'Engineered AI Prompts & Agents'), ('saas_plugin', 'SaaS Extension Microservices')], default='code_template', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('download_url', models.URLField(max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('compiled_spec_manifest', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Digital Product',
                'verbose_name_plural': 'Digital Products',
            },
        ),
        migrations.CreateModel(
            name='LicensePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(max_length=64, unique=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee_deducted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_payout_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_purchases', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales_history', to='marketplace_api.digitalproduct')),
            ],
            options={
                'verbose_name': 'License Purchase',
                'verbose_name_plural': 'License Purchases',
            },
        ),
    ]
