# Generated by Django 6.0.4 on 2026-05-20 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('asset_class', models.CharField(choices=[('multifamily', 'Multifamily'), ('industrial', 'Industrial'), ('retail', 'Retail'), ('office', 'Office')], default='multifamily', max_length=50)),
                ('units', models.IntegerField(default=1)),
                ('implied_cap_rate', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Property Listing',
                'verbose_name_plural': 'Property Listings',
            },
        ),
        migrations.CreateModel(
            name='BuyerMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(choices=[('multifamily', 'Multifamily'), ('industrial', 'Industrial'), ('retail', 'Retail'), ('office', 'Office')], default='multifamily', max_length=50)),
                ('target_cap_rate_min', models.FloatField(default=5.0)),
                ('buy_box_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_mandates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyer Mandate',
                'verbose_name_plural': 'Buyer Mandates',
            },
        ),
        migrations.CreateModel(
            name='UnderwritingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_potential_rent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_operating_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('risk_factors_detected', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='underwriting_report', to='real_estate_api.propertylisting')),
            ],
            options={
                'verbose_name': 'Underwriting Report',
                'verbose_name_plural': 'Underwriting Reports',
            },
        ),
    ]
