# Generated by Django 6.0.4 on 2026-05-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_urls', models.JSONField(default=list, help_text='Array of target competitor domain strings.')),
                ('market_positioning_landscape', models.JSONField(default=dict, help_text='Synthesized themes, identified gaps, and keywords.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Competitor Audit',
                'verbose_name_plural': 'Competitor Audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadICPScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_url', models.URLField(max_length=500)),
                ('icp_definition_text', models.TextField(help_text='The core definition of the target client profile.')),
                ('icp_alignment_score', models.FloatField(help_text='Calculated vector similarity score between 0.0 and 1.0.')),
                ('qualification_signals', models.JSONField(default=dict, help_text='Structured dict containing firmographics, pain points, etc.')),
                ('recommended_outreach_angle', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead ICP Score',
                'verbose_name_plural': 'Lead ICP Scores',
                'ordering': ['-created_at'],
            },
        ),
    ]
